/* Generated by scripts/gen-gl-headers.py from the Khronos registry (gl.xml) and spec/abi.json: do not edit. */
#ifndef __gl3platform_h_
#define __gl3platform_h_
#include <KHR/khrplatform.h>
#ifndef GL_APICALL
#define GL_APICALL
#endif
#ifndef GL_APIENTRY
#define GL_APIENTRY
#endif
#endif
