/* Generated by scripts/gen-gl-headers.py from the Khronos registry (gl.xml) and spec/abi.json: do not edit. */
/*
 * The GLES 3.0 API on the gasm:gl imports. Most functions are a call; the rest
 * adapt GL's C conventions to the ABI: name arrays, string arrays, the pixel
 * store (data lengths are exact: the runner checks them), glGetString caching and
 * glMapBufferRange emulated in guest memory (WebGL has no mapping).
 *
 * SPDX-License-Identifier: MIT
 */
#include <stdlib.h>
#include <string.h>

#include "gasm.h"
#include <GLES3/gl3.h>

static GLenum c_error;   /* errors found here (no binary formats, bad indices) */

/* ---- the pixel store and the pack/unpack buffers, mirrored to compute exact lengths ---- */

typedef struct { int alignment, row_length, image_height, skip_pixels, skip_rows, skip_images; } store;
static store unpack = { 4, 0, 0, 0, 0, 0 }, pack = { 4, 0, 0, 0, 0, 0 };
static GLuint unpack_buffer, pack_buffer;

static void track_buffer(GLenum target, GLuint buffer) {
    if (target == GL_PIXEL_UNPACK_BUFFER) unpack_buffer = buffer;
    if (target == GL_PIXEL_PACK_BUFFER) pack_buffer = buffer;
}

static void track_store(GLenum pname, GLint v) {
    switch (pname) {
    case GL_UNPACK_ALIGNMENT: unpack.alignment = v; break;
    case GL_UNPACK_ROW_LENGTH: unpack.row_length = v; break;
    case GL_UNPACK_IMAGE_HEIGHT: unpack.image_height = v; break;
    case GL_UNPACK_SKIP_PIXELS: unpack.skip_pixels = v; break;
    case GL_UNPACK_SKIP_ROWS: unpack.skip_rows = v; break;
    case GL_UNPACK_SKIP_IMAGES: unpack.skip_images = v; break;
    case GL_PACK_ALIGNMENT: pack.alignment = v; break;
    case GL_PACK_ROW_LENGTH: pack.row_length = v; break;
    case GL_PACK_SKIP_PIXELS: pack.skip_pixels = v; break;
    case GL_PACK_SKIP_ROWS: pack.skip_rows = v; break;
    }
}

static uint32_t pixel_bytes(GLenum format, GLenum type) {
    switch (type) {
    case GL_UNSIGNED_SHORT_5_6_5: case GL_UNSIGNED_SHORT_4_4_4_4: case GL_UNSIGNED_SHORT_5_5_5_1: return 2;
    case GL_UNSIGNED_INT_2_10_10_10_REV: case GL_UNSIGNED_INT_10F_11F_11F_REV:
    case GL_UNSIGNED_INT_5_9_9_9_REV: case GL_UNSIGNED_INT_24_8: return 4;
    case GL_FLOAT_32_UNSIGNED_INT_24_8_REV: return 8;
    }
    uint32_t size = 0, comps = 0;
    switch (type) {
    case GL_BYTE: case GL_UNSIGNED_BYTE: size = 1; break;
    case GL_SHORT: case GL_UNSIGNED_SHORT: case GL_HALF_FLOAT: size = 2; break;
    case GL_INT: case GL_UNSIGNED_INT: case GL_FLOAT: size = 4; break;
    }
    switch (format) {
    case GL_RED: case GL_RED_INTEGER: case GL_ALPHA: case GL_LUMINANCE: case GL_DEPTH_COMPONENT: comps = 1; break;
    case GL_RG: case GL_RG_INTEGER: case GL_LUMINANCE_ALPHA: case GL_DEPTH_STENCIL: comps = 2; break;
    case GL_RGB: case GL_RGB_INTEGER: comps = 3; break;
    case GL_RGBA: case GL_RGBA_INTEGER: comps = 4; break;
    }
    return size * comps;
}

/* Bytes of a w×h×d image under a pixel store (GLES 3.0 3.7.1; same formula in the runners). */
static uint32_t image_bytes(const store *s, GLsizei w, GLsizei h, GLsizei d, GLenum format, GLenum type) {
    uint32_t bpp = pixel_bytes(format, type);
    if (w <= 0 || h <= 0 || d <= 0 || !bpp || s->alignment <= 0) return 0;
    uint32_t row_len = s->row_length > 0 ? (uint32_t)s->row_length : (uint32_t)w;
    uint32_t a = (uint32_t)s->alignment;
    uint32_t row = (row_len * bpp + a - 1) / a * a;
    uint32_t img_h = s->image_height > 0 ? (uint32_t)s->image_height : (uint32_t)h;
    uint32_t img = row * img_h;
    return (uint32_t)s->skip_images * img + (uint32_t)(d - 1) * img + (uint32_t)s->skip_rows * row +
           (uint32_t)(h - 1) * row + (uint32_t)s->skip_pixels * bpp + (uint32_t)w * bpp;
}

/* with an unpack buffer bound, "pixels" is an offset into it: no pointer, the offset as len */
#define UNPACK_PTR(p) (unpack_buffer ? (const void *)0 : (p))
#define UNPACK_LEN(p, w, h, d, f, t) (unpack_buffer ? (uint32_t)(uintptr_t)(p) : (p) ? image_bytes(&unpack, w, h, d, f, t) : 0)

/* ---- strings ---------------------------------------------------------------------------- */

static void shader_source(GLuint shader, GLsizei count, const GLchar *const *strings, const GLint *lengths) {
    size_t total = 0;
    for (GLsizei i = 0; i < count; i++)
        total += lengths && lengths[i] >= 0 ? (size_t)lengths[i] : strlen(strings[i]);
    char *all = (char *)malloc(total + 1), *p = all;
    if (!all) { c_error = GL_OUT_OF_MEMORY; return; }
    for (GLsizei i = 0; i < count; i++) {
        size_t n = lengths && lengths[i] >= 0 ? (size_t)lengths[i] : strlen(strings[i]);
        memcpy(p, strings[i], n);
        p += n;
    }
    gasm_gl_shader_source(shader, all, (uint32_t)total);
    free(all);
}

static void feedback_varyings(GLuint program, GLsizei count, const GLchar *const *names, GLenum mode) {
    size_t total = 0;
    for (GLsizei i = 0; i < count; i++) total += strlen(names[i]) + 1;
    char *all = (char *)malloc(total ? total : 1), *p = all;
    if (!all) { c_error = GL_OUT_OF_MEMORY; return; }
    for (GLsizei i = 0; i < count; i++) {
        size_t n = strlen(names[i]) + 1;
        memcpy(p, names[i], n);
        p += n;
    }
    gasm_gl_transform_feedback_varyings(program, all, (uint32_t)total, (uint32_t)count, mode);
    free(all);
}

/* The "returns the full length, copies if it fits" imports, as GL's truncating copies. */
typedef int32_t (*text_fn)(uint32_t, void *, uint32_t);
static void truncated(text_fn f, GLuint object, GLsizei size, GLsizei *length, GLchar *out) {
    int32_t n = f(object, 0, 0);
    if (n < 0 || size <= 0) { if (length) *length = 0; return; }
    char *tmp = (char *)malloc((size_t)n + 1);
    if (!tmp) { if (length) *length = 0; return; }
    f(object, tmp, (uint32_t)n);
    int32_t k = n < size - 1 ? n : size - 1;
    memcpy(out, tmp, (size_t)k);
    out[k] = 0;
    if (length) *length = k;
    free(tmp);
}
typedef int32_t (*text2_fn)(uint32_t, uint32_t, void *, uint32_t);
static void truncated2(text2_fn f, GLuint object, GLuint index, GLsizei size, GLsizei *length, GLchar *out) {
    int32_t n = f(object, index, 0, 0);
    if (n < 0 || size <= 0) { if (length) *length = 0; return; }
    char *tmp = (char *)malloc((size_t)n + 1);
    if (!tmp) { if (length) *length = 0; return; }
    f(object, index, tmp, (uint32_t)n);
    int32_t k = n < size - 1 ? n : size - 1;
    memcpy(out, tmp, (size_t)k);
    out[k] = 0;
    if (length) *length = k;
    free(tmp);
}
typedef int32_t (*info_fn)(uint32_t, uint32_t, void *, uint32_t, void *);
static void active_info(info_fn f, GLuint program, GLuint index, GLsizei size, GLsizei *length, GLint *out_size, GLenum *out_type, GLchar *name) {
    int32_t info[2] = { 0, 0 };
    int32_t n = f(program, index, 0, 0, info);
    if (n < 0) { if (length) *length = 0; return; }
    char *tmp = (char *)malloc((size_t)n + 1);
    if (!tmp) return;
    f(program, index, tmp, (uint32_t)n, info);
    int32_t k = size > 0 ? (n < size - 1 ? n : size - 1) : 0;
    if (size > 0) { memcpy(name, tmp, (size_t)k); name[k] = 0; }
    if (length) *length = k;
    if (out_size) *out_size = info[0];
    if (out_type) *out_type = (GLenum)info[1];
    free(tmp);
}

/* glGetString returns pointers that stay valid: one cached copy per name */
static const GLubyte *get_string(GLenum name) {
    static const GLenum names[] = { GL_VENDOR, GL_RENDERER, GL_VERSION, GL_SHADING_LANGUAGE_VERSION, GL_EXTENSIONS };
    static char *cache[5];
    for (int i = 0; i < 5; i++) {
        if (names[i] != name) continue;
        if (!cache[i]) {
            int32_t n = gasm_gl_get_string(name, 0, 0);
            if (n < 0) return 0;
            cache[i] = (char *)calloc((size_t)n + 1, 1);
            if (cache[i]) gasm_gl_get_string(name, cache[i], (uint32_t)n);
        }
        return (const GLubyte *)cache[i];
    }
    c_error = GL_INVALID_ENUM;
    return 0;
}

static char **ext_list;
static unsigned ext_count;
static unsigned extension_count(void) {
    if (!ext_list) {
        const char *all = (const char *)get_string(GL_EXTENSIONS);
        size_t len = all ? strlen(all) : 0;
        char *copy = (char *)malloc(len + 1);
        if (!copy) return 0;
        memcpy(copy, all ? all : "", len + 1);
        ext_list = (char **)calloc(len / 2 + 2, sizeof *ext_list);
        for (char *t = strtok(copy, " "); t && ext_list; t = strtok(0, " ")) ext_list[ext_count++] = t;
    }
    return ext_count;
}
static const GLubyte *extension(GLuint index) {
    if (index >= extension_count()) { c_error = GL_INVALID_VALUE; return 0; }
    return (const GLubyte *)ext_list[index];
}

/* ---- glMapBufferRange: a guest-memory copy, uploaded on unmap or flush ------------------- */

typedef struct { GLenum target; void *ptr; GLintptr offset; GLsizeiptr length; GLbitfield access; } mapping;
static mapping maps[8];

static mapping *mapping_for(GLenum target) {
    for (int i = 0; i < 8; i++)
        if (maps[i].ptr && maps[i].target == target) return &maps[i];
    return 0;
}

static void *map_range(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access) {
    if (mapping_for(target) || length <= 0 || offset < 0) { c_error = GL_INVALID_OPERATION; return 0; }
    for (int i = 0; i < 8; i++) {
        if (maps[i].ptr) continue;
        void *p = malloc((size_t)length);
        if (!p) { c_error = GL_OUT_OF_MEMORY; return 0; }
        if ((access & GL_MAP_READ_BIT) || !(access & (GL_MAP_INVALIDATE_RANGE_BIT | GL_MAP_INVALIDATE_BUFFER_BIT)))
            gasm_gl_get_buffer_sub_data(target, (uint32_t)offset, p, (uint32_t)length);   /* the current contents */
        maps[i] = (mapping){ target, p, offset, length, access };
        return p;
    }
    c_error = GL_OUT_OF_MEMORY;
    return 0;
}

static void flush_mapped(GLenum target, GLintptr offset, GLsizeiptr length) {
    mapping *m = mapping_for(target);
    if (!m || offset < 0 || offset + length > m->length) { c_error = GL_INVALID_VALUE; return; }
    gasm_gl_buffer_sub_data(target, (uint32_t)(m->offset + offset), (char *)m->ptr + offset, (uint32_t)length);
}

static GLboolean unmap(GLenum target) {
    mapping *m = mapping_for(target);
    if (!m) { c_error = GL_INVALID_OPERATION; return GL_FALSE; }
    if ((m->access & GL_MAP_WRITE_BIT) && !(m->access & GL_MAP_FLUSH_EXPLICIT_BIT))
        gasm_gl_buffer_sub_data(target, (uint32_t)m->offset, m->ptr, (uint32_t)m->length);
    free(m->ptr);
    m->ptr = 0;
    return GL_TRUE;
}

/* ---- the API ------------------------------------------------------------------------------ */

void GL_APIENTRY glActiveTexture(GLenum texture) {
    gasm_gl_active_texture(texture);
}

void GL_APIENTRY glAttachShader(GLuint program, GLuint shader) {
    gasm_gl_attach_shader(program, shader);
}

void GL_APIENTRY glBindAttribLocation(GLuint program, GLuint index, const GLchar * name) {
    gasm_gl_bind_attrib_location(program, index, name, (uint32_t)strlen(name));
}

void GL_APIENTRY glBindBuffer(GLenum target, GLuint buffer) {
    track_buffer(target, buffer);
    gasm_gl_bind_buffer(target, buffer);
}

void GL_APIENTRY glBindFramebuffer(GLenum target, GLuint framebuffer) {
    gasm_gl_bind_framebuffer(target, framebuffer);
}

void GL_APIENTRY glBindRenderbuffer(GLenum target, GLuint renderbuffer) {
    gasm_gl_bind_renderbuffer(target, renderbuffer);
}

void GL_APIENTRY glBindTexture(GLenum target, GLuint texture) {
    gasm_gl_bind_texture(target, texture);
}

void GL_APIENTRY glBlendColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) {
    gasm_gl_blend_color(red, green, blue, alpha);
}

void GL_APIENTRY glBlendEquation(GLenum mode) {
    gasm_gl_blend_equation(mode);
}

void GL_APIENTRY glBlendEquationSeparate(GLenum modeRGB, GLenum modeAlpha) {
    gasm_gl_blend_equation_separate(modeRGB, modeAlpha);
}

void GL_APIENTRY glBlendFunc(GLenum sfactor, GLenum dfactor) {
    gasm_gl_blend_func(sfactor, dfactor);
}

void GL_APIENTRY glBlendFuncSeparate(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha) {
    gasm_gl_blend_func_separate(sfactorRGB, dfactorRGB, sfactorAlpha, dfactorAlpha);
}

void GL_APIENTRY glBufferData(GLenum target, GLsizeiptr size, const void * data, GLenum usage) {
    gasm_gl_buffer_data(target, data, (uint32_t)size, usage);
}

void GL_APIENTRY glBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, const void * data) {
    gasm_gl_buffer_sub_data(target, (uint32_t)offset, data, (uint32_t)size);
}

GLenum GL_APIENTRY glCheckFramebufferStatus(GLenum target) {
    return (GLenum)gasm_gl_check_framebuffer_status(target);
}

void GL_APIENTRY glClear(GLbitfield mask) {
    gasm_gl_clear(mask);
}

void GL_APIENTRY glClearColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) {
    gasm_gl_clear_color(red, green, blue, alpha);
}

void GL_APIENTRY glClearDepthf(GLfloat d) {
    gasm_gl_clear_depthf(d);
}

void GL_APIENTRY glClearStencil(GLint s) {
    gasm_gl_clear_stencil(s);
}

void GL_APIENTRY glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha) {
    gasm_gl_color_mask(red, green, blue, alpha);
}

void GL_APIENTRY glCompileShader(GLuint shader) {
    gasm_gl_compile_shader(shader);
}

void GL_APIENTRY glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void * data) {
    gasm_gl_compressed_tex_image_2d(target, level, internalformat, width, height, border, data, (uint32_t)imageSize);
}

void GL_APIENTRY glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void * data) {
    gasm_gl_compressed_tex_sub_image_2d(target, level, xoffset, yoffset, width, height, format, data, (uint32_t)imageSize);
}

void GL_APIENTRY glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border) {
    gasm_gl_copy_tex_image_2d(target, level, internalformat, x, y, width, height, border);
}

void GL_APIENTRY glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height) {
    gasm_gl_copy_tex_sub_image_2d(target, level, xoffset, yoffset, x, y, width, height);
}

GLuint GL_APIENTRY glCreateProgram(void) {
    return (GLuint)gasm_gl_create_program();
}

GLuint GL_APIENTRY glCreateShader(GLenum type) {
    return (GLuint)gasm_gl_create_shader(type);
}

void GL_APIENTRY glCullFace(GLenum mode) {
    gasm_gl_cull_face(mode);
}

void GL_APIENTRY glDeleteBuffers(GLsizei n, const GLuint * buffers) {
    for (GLsizei i = 0; i < n; i++) gasm_gl_delete_buffer(buffers[i]);
}

void GL_APIENTRY glDeleteFramebuffers(GLsizei n, const GLuint * framebuffers) {
    for (GLsizei i = 0; i < n; i++) gasm_gl_delete_framebuffer(framebuffers[i]);
}

void GL_APIENTRY glDeleteProgram(GLuint program) {
    gasm_gl_delete_program(program);
}

void GL_APIENTRY glDeleteRenderbuffers(GLsizei n, const GLuint * renderbuffers) {
    for (GLsizei i = 0; i < n; i++) gasm_gl_delete_renderbuffer(renderbuffers[i]);
}

void GL_APIENTRY glDeleteShader(GLuint shader) {
    gasm_gl_delete_shader(shader);
}

void GL_APIENTRY glDeleteTextures(GLsizei n, const GLuint * textures) {
    for (GLsizei i = 0; i < n; i++) gasm_gl_delete_texture(textures[i]);
}

void GL_APIENTRY glDepthFunc(GLenum func) {
    gasm_gl_depth_func(func);
}

void GL_APIENTRY glDepthMask(GLboolean flag) {
    gasm_gl_depth_mask(flag);
}

void GL_APIENTRY glDepthRangef(GLfloat n, GLfloat f) {
    gasm_gl_depth_rangef(n, f);
}

void GL_APIENTRY glDetachShader(GLuint program, GLuint shader) {
    gasm_gl_detach_shader(program, shader);
}

void GL_APIENTRY glDisable(GLenum cap) {
    gasm_gl_disable(cap);
}

void GL_APIENTRY glDisableVertexAttribArray(GLuint index) {
    gasm_gl_disable_vertex_attrib_array(index);
}

void GL_APIENTRY glDrawArrays(GLenum mode, GLint first, GLsizei count) {
    gasm_gl_draw_arrays(mode, first, count);
}

void GL_APIENTRY glDrawElements(GLenum mode, GLsizei count, GLenum type, const void * indices) {
    gasm_gl_draw_elements(mode, count, type, (uint32_t)(uintptr_t)indices);
}

void GL_APIENTRY glEnable(GLenum cap) {
    gasm_gl_enable(cap);
}

void GL_APIENTRY glEnableVertexAttribArray(GLuint index) {
    gasm_gl_enable_vertex_attrib_array(index);
}

void GL_APIENTRY glFinish(void) {
    gasm_gl_finish();
}

void GL_APIENTRY glFlush(void) {
    gasm_gl_flush();
}

void GL_APIENTRY glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer) {
    gasm_gl_framebuffer_renderbuffer(target, attachment, renderbuffertarget, renderbuffer);
}

void GL_APIENTRY glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level) {
    gasm_gl_framebuffer_texture_2d(target, attachment, textarget, texture, level);
}

void GL_APIENTRY glFrontFace(GLenum mode) {
    gasm_gl_front_face(mode);
}

void GL_APIENTRY glGenBuffers(GLsizei n, GLuint * buffers) {
    for (GLsizei i = 0; i < n; i++) buffers[i] = gasm_gl_create_buffer();
}

void GL_APIENTRY glGenerateMipmap(GLenum target) {
    gasm_gl_generate_mipmap(target);
}

void GL_APIENTRY glGenFramebuffers(GLsizei n, GLuint * framebuffers) {
    for (GLsizei i = 0; i < n; i++) framebuffers[i] = gasm_gl_create_framebuffer();
}

void GL_APIENTRY glGenRenderbuffers(GLsizei n, GLuint * renderbuffers) {
    for (GLsizei i = 0; i < n; i++) renderbuffers[i] = gasm_gl_create_renderbuffer();
}

void GL_APIENTRY glGenTextures(GLsizei n, GLuint * textures) {
    for (GLsizei i = 0; i < n; i++) textures[i] = gasm_gl_create_texture();
}

void GL_APIENTRY glGetActiveAttrib(GLuint program, GLuint index, GLsizei bufSize, GLsizei * length, GLint * size, GLenum * type, GLchar * name) {
    active_info(gasm_gl_get_active_attrib, program, index, bufSize, length, size, type, name);
}

void GL_APIENTRY glGetActiveUniform(GLuint program, GLuint index, GLsizei bufSize, GLsizei * length, GLint * size, GLenum * type, GLchar * name) {
    active_info(gasm_gl_get_active_uniform, program, index, bufSize, length, size, type, name);
}

void GL_APIENTRY glGetAttachedShaders(GLuint program, GLsizei maxCount, GLsizei * count, GLuint * shaders) {
    int n = gasm_gl_get_attached_shaders(program, shaders, (uint32_t)maxCount);
    if (count) *count = n < maxCount ? n : maxCount;
}

GLint GL_APIENTRY glGetAttribLocation(GLuint program, const GLchar * name) {
    return gasm_gl_get_attrib_location(program, name, (uint32_t)strlen(name));
}

void GL_APIENTRY glGetBooleanv(GLenum pname, GLboolean * data) {
    GLint v[64];
    int n = gasm_gl_get_integerv(pname, v, 64);
    for (int i = 0; i < n && i < 64; i++) data[i] = v[i] ? GL_TRUE : GL_FALSE;
}

void GL_APIENTRY glGetBufferParameteriv(GLenum target, GLenum pname, GLint * params) {
    *params = gasm_gl_get_buffer_parameteriv(target, pname);
}

GLenum GL_APIENTRY glGetError(void) {
    if (c_error) { GLenum e = c_error; c_error = 0; return e; }
    return gasm_gl_get_error();
}

void GL_APIENTRY glGetFloatv(GLenum pname, GLfloat * data) {
    gasm_gl_get_floatv(pname, data, 64);
}

void GL_APIENTRY glGetFramebufferAttachmentParameteriv(GLenum target, GLenum attachment, GLenum pname, GLint * params) {
    *params = gasm_gl_get_framebuffer_attachment_parameteriv(target, attachment, pname);
}

void GL_APIENTRY glGetIntegerv(GLenum pname, GLint * data) {
    if (pname == GL_NUM_EXTENSIONS) { *data = (GLint)extension_count(); return; }
    gasm_gl_get_integerv(pname, data, 64);
}

void GL_APIENTRY glGetProgramiv(GLuint program, GLenum pname, GLint * params) {
    *params = gasm_gl_get_programiv(program, pname);
}

void GL_APIENTRY glGetProgramInfoLog(GLuint program, GLsizei bufSize, GLsizei * length, GLchar * infoLog) {
    truncated(gasm_gl_get_program_info_log, program, bufSize, length, infoLog);
}

void GL_APIENTRY glGetRenderbufferParameteriv(GLenum target, GLenum pname, GLint * params) {
    *params = gasm_gl_get_renderbuffer_parameteriv(target, pname);
}

void GL_APIENTRY glGetShaderiv(GLuint shader, GLenum pname, GLint * params) {
    *params = gasm_gl_get_shaderiv(shader, pname);
}

void GL_APIENTRY glGetShaderInfoLog(GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * infoLog) {
    truncated(gasm_gl_get_shader_info_log, shader, bufSize, length, infoLog);
}

void GL_APIENTRY glGetShaderPrecisionFormat(GLenum shadertype, GLenum precisiontype, GLint * range, GLint * precision) {
    GLint v[3];
    gasm_gl_get_shader_precision_format(shadertype, precisiontype, v);
    range[0] = v[0];
    range[1] = v[1];
    *precision = v[2];
}

void GL_APIENTRY glGetShaderSource(GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * source) {
    truncated(gasm_gl_get_shader_source, shader, bufSize, length, source);
}

const GLubyte * GL_APIENTRY glGetString(GLenum name) {
    return get_string(name);
}

void GL_APIENTRY glGetTexParameterfv(GLenum target, GLenum pname, GLfloat * params) {
    *params = gasm_gl_get_tex_parameterfv(target, pname);
}

void GL_APIENTRY glGetTexParameteriv(GLenum target, GLenum pname, GLint * params) {
    *params = gasm_gl_get_tex_parameteriv(target, pname);
}

void GL_APIENTRY glGetUniformfv(GLuint program, GLint location, GLfloat * params) {
    gasm_gl_get_uniformfv(program, location, params, 16);
}

void GL_APIENTRY glGetUniformiv(GLuint program, GLint location, GLint * params) {
    gasm_gl_get_uniformiv(program, location, params, 16);
}

GLint GL_APIENTRY glGetUniformLocation(GLuint program, const GLchar * name) {
    return gasm_gl_get_uniform_location(program, name, (uint32_t)strlen(name));
}

void GL_APIENTRY glGetVertexAttribfv(GLuint index, GLenum pname, GLfloat * params) {
    gasm_gl_get_vertex_attribfv(index, pname, params, 4);
}

void GL_APIENTRY glGetVertexAttribiv(GLuint index, GLenum pname, GLint * params) {
    *params = gasm_gl_get_vertex_attribiv(index, pname);
}

void GL_APIENTRY glGetVertexAttribPointerv(GLuint index, GLenum pname, void ** pointer) {
    *pointer = (void *)(uintptr_t)gasm_gl_get_vertex_attrib_offset(index, pname);
}

void GL_APIENTRY glHint(GLenum target, GLenum mode) {
    gasm_gl_hint(target, mode);
}

GLboolean GL_APIENTRY glIsBuffer(GLuint buffer) {
    return (GLboolean)gasm_gl_is_buffer(buffer);
}

GLboolean GL_APIENTRY glIsEnabled(GLenum cap) {
    return (GLboolean)gasm_gl_is_enabled(cap);
}

GLboolean GL_APIENTRY glIsFramebuffer(GLuint framebuffer) {
    return (GLboolean)gasm_gl_is_framebuffer(framebuffer);
}

GLboolean GL_APIENTRY glIsProgram(GLuint program) {
    return (GLboolean)gasm_gl_is_program(program);
}

GLboolean GL_APIENTRY glIsRenderbuffer(GLuint renderbuffer) {
    return (GLboolean)gasm_gl_is_renderbuffer(renderbuffer);
}

GLboolean GL_APIENTRY glIsShader(GLuint shader) {
    return (GLboolean)gasm_gl_is_shader(shader);
}

GLboolean GL_APIENTRY glIsTexture(GLuint texture) {
    return (GLboolean)gasm_gl_is_texture(texture);
}

void GL_APIENTRY glLineWidth(GLfloat width) {
    gasm_gl_line_width(width);
}

void GL_APIENTRY glLinkProgram(GLuint program) {
    gasm_gl_link_program(program);
}

void GL_APIENTRY glPixelStorei(GLenum pname, GLint param) {
    track_store(pname, param);
    gasm_gl_pixel_storei(pname, param);
}

void GL_APIENTRY glPolygonOffset(GLfloat factor, GLfloat units) {
    gasm_gl_polygon_offset(factor, units);
}

void GL_APIENTRY glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void * pixels) {
    if (pack_buffer) { gasm_gl_read_pixels(x, y, width, height, format, type, pixels, 0); return; }
    gasm_gl_read_pixels(x, y, width, height, format, type, pixels, image_bytes(&pack, width, height, 1, format, type));
}

void GL_APIENTRY glReleaseShaderCompiler(void) {
    
}

void GL_APIENTRY glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height) {
    gasm_gl_renderbuffer_storage(target, internalformat, width, height);
}

void GL_APIENTRY glSampleCoverage(GLfloat value, GLboolean invert) {
    gasm_gl_sample_coverage(value, invert);
}

void GL_APIENTRY glScissor(GLint x, GLint y, GLsizei width, GLsizei height) {
    gasm_gl_scissor(x, y, width, height);
}

void GL_APIENTRY glShaderBinary(GLsizei count, const GLuint * shaders, GLenum binaryformat, const void * binary, GLsizei length) {
    (void)count;
    (void)shaders;
    (void)binaryformat;
    (void)binary;
    (void)length;
    c_error = GL_INVALID_ENUM;   /* WebGL has no shader formats */
}

void GL_APIENTRY glShaderSource(GLuint shader, GLsizei count, const GLchar *const* string, const GLint * length) {
    shader_source(shader, count, string, length);
}

void GL_APIENTRY glStencilFunc(GLenum func, GLint ref, GLuint mask) {
    gasm_gl_stencil_func(func, ref, mask);
}

void GL_APIENTRY glStencilFuncSeparate(GLenum face, GLenum func, GLint ref, GLuint mask) {
    gasm_gl_stencil_func_separate(face, func, ref, mask);
}

void GL_APIENTRY glStencilMask(GLuint mask) {
    gasm_gl_stencil_mask(mask);
}

void GL_APIENTRY glStencilMaskSeparate(GLenum face, GLuint mask) {
    gasm_gl_stencil_mask_separate(face, mask);
}

void GL_APIENTRY glStencilOp(GLenum fail, GLenum zfail, GLenum zpass) {
    gasm_gl_stencil_op(fail, zfail, zpass);
}

void GL_APIENTRY glStencilOpSeparate(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass) {
    gasm_gl_stencil_op_separate(face, sfail, dpfail, dppass);
}

void GL_APIENTRY glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void * pixels) {
    gasm_gl_tex_image_2d(target, level, internalformat, width, height, border, format, type, UNPACK_PTR(pixels), UNPACK_LEN(pixels, width, height, 1, format, type));
}

void GL_APIENTRY glTexParameterf(GLenum target, GLenum pname, GLfloat param) {
    gasm_gl_tex_parameterf(target, pname, param);
}

void GL_APIENTRY glTexParameterfv(GLenum target, GLenum pname, const GLfloat * params) {
    gasm_gl_tex_parameterf(target, pname, params[0]);
}

void GL_APIENTRY glTexParameteri(GLenum target, GLenum pname, GLint param) {
    gasm_gl_tex_parameteri(target, pname, param);
}

void GL_APIENTRY glTexParameteriv(GLenum target, GLenum pname, const GLint * params) {
    gasm_gl_tex_parameteri(target, pname, params[0]);
}

void GL_APIENTRY glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void * pixels) {
    gasm_gl_tex_sub_image_2d(target, level, xoffset, yoffset, width, height, format, type, UNPACK_PTR(pixels), UNPACK_LEN(pixels, width, height, 1, format, type));
}

void GL_APIENTRY glUniform1f(GLint location, GLfloat v0) {
    gasm_gl_uniform1f(location, v0);
}

void GL_APIENTRY glUniform1fv(GLint location, GLsizei count, const GLfloat * value) {
    gasm_gl_uniform1fv(location, count, value);
}

void GL_APIENTRY glUniform1i(GLint location, GLint v0) {
    gasm_gl_uniform1i(location, v0);
}

void GL_APIENTRY glUniform1iv(GLint location, GLsizei count, const GLint * value) {
    gasm_gl_uniform1iv(location, count, value);
}

void GL_APIENTRY glUniform2f(GLint location, GLfloat v0, GLfloat v1) {
    gasm_gl_uniform2f(location, v0, v1);
}

void GL_APIENTRY glUniform2fv(GLint location, GLsizei count, const GLfloat * value) {
    gasm_gl_uniform2fv(location, count, value);
}

void GL_APIENTRY glUniform2i(GLint location, GLint v0, GLint v1) {
    gasm_gl_uniform2i(location, v0, v1);
}

void GL_APIENTRY glUniform2iv(GLint location, GLsizei count, const GLint * value) {
    gasm_gl_uniform2iv(location, count, value);
}

void GL_APIENTRY glUniform3f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2) {
    gasm_gl_uniform3f(location, v0, v1, v2);
}

void GL_APIENTRY glUniform3fv(GLint location, GLsizei count, const GLfloat * value) {
    gasm_gl_uniform3fv(location, count, value);
}

void GL_APIENTRY glUniform3i(GLint location, GLint v0, GLint v1, GLint v2) {
    gasm_gl_uniform3i(location, v0, v1, v2);
}

void GL_APIENTRY glUniform3iv(GLint location, GLsizei count, const GLint * value) {
    gasm_gl_uniform3iv(location, count, value);
}

void GL_APIENTRY glUniform4f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3) {
    gasm_gl_uniform4f(location, v0, v1, v2, v3);
}

void GL_APIENTRY glUniform4fv(GLint location, GLsizei count, const GLfloat * value) {
    gasm_gl_uniform4fv(location, count, value);
}

void GL_APIENTRY glUniform4i(GLint location, GLint v0, GLint v1, GLint v2, GLint v3) {
    gasm_gl_uniform4i(location, v0, v1, v2, v3);
}

void GL_APIENTRY glUniform4iv(GLint location, GLsizei count, const GLint * value) {
    gasm_gl_uniform4iv(location, count, value);
}

void GL_APIENTRY glUniformMatrix2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) {
    gasm_gl_uniform_matrix2fv(location, count, transpose, value);
}

void GL_APIENTRY glUniformMatrix3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) {
    gasm_gl_uniform_matrix3fv(location, count, transpose, value);
}

void GL_APIENTRY glUniformMatrix4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) {
    gasm_gl_uniform_matrix4fv(location, count, transpose, value);
}

void GL_APIENTRY glUseProgram(GLuint program) {
    gasm_gl_use_program(program);
}

void GL_APIENTRY glValidateProgram(GLuint program) {
    gasm_gl_validate_program(program);
}

void GL_APIENTRY glVertexAttrib1f(GLuint index, GLfloat x) {
    gasm_gl_vertex_attrib4f(index, x, 0, 0, 1);
}

void GL_APIENTRY glVertexAttrib1fv(GLuint index, const GLfloat * v) {
    gasm_gl_vertex_attrib4f(index, v[0], 0, 0, 1);
}

void GL_APIENTRY glVertexAttrib2f(GLuint index, GLfloat x, GLfloat y) {
    gasm_gl_vertex_attrib4f(index, x, y, 0, 1);
}

void GL_APIENTRY glVertexAttrib2fv(GLuint index, const GLfloat * v) {
    gasm_gl_vertex_attrib4f(index, v[0], v[1], 0, 1);
}

void GL_APIENTRY glVertexAttrib3f(GLuint index, GLfloat x, GLfloat y, GLfloat z) {
    gasm_gl_vertex_attrib4f(index, x, y, z, 1);
}

void GL_APIENTRY glVertexAttrib3fv(GLuint index, const GLfloat * v) {
    gasm_gl_vertex_attrib4f(index, v[0], v[1], v[2], 1);
}

void GL_APIENTRY glVertexAttrib4f(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w) {
    gasm_gl_vertex_attrib4f(index, x, y, z, w);
}

void GL_APIENTRY glVertexAttrib4fv(GLuint index, const GLfloat * v) {
    gasm_gl_vertex_attrib4f(index, v[0], v[1], v[2], v[3]);
}

void GL_APIENTRY glVertexAttribPointer(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void * pointer) {
    gasm_gl_vertex_attrib_pointer(index, size, type, normalized, stride, (uint32_t)(uintptr_t)pointer);
}

void GL_APIENTRY glViewport(GLint x, GLint y, GLsizei width, GLsizei height) {
    gasm_gl_viewport(x, y, width, height);
}

void GL_APIENTRY glReadBuffer(GLenum src) {
    gasm_gl_read_buffer(src);
}

void GL_APIENTRY glDrawRangeElements(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void * indices) {
    gasm_gl_draw_range_elements(mode, start, end, count, type, (uint32_t)(uintptr_t)indices);
}

void GL_APIENTRY glTexImage3D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void * pixels) {
    gasm_gl_tex_image_3d(target, level, internalformat, width, height, depth, border, format, type, UNPACK_PTR(pixels), UNPACK_LEN(pixels, width, height, depth, format, type));
}

void GL_APIENTRY glTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void * pixels) {
    gasm_gl_tex_sub_image_3d(target, level, xoffset, yoffset, zoffset, width, height, depth, format, type, UNPACK_PTR(pixels), UNPACK_LEN(pixels, width, height, depth, format, type));
}

void GL_APIENTRY glCopyTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height) {
    gasm_gl_copy_tex_sub_image_3d(target, level, xoffset, yoffset, zoffset, x, y, width, height);
}

void GL_APIENTRY glCompressedTexImage3D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void * data) {
    gasm_gl_compressed_tex_image_3d(target, level, internalformat, width, height, depth, border, data, (uint32_t)imageSize);
}

void GL_APIENTRY glCompressedTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void * data) {
    gasm_gl_compressed_tex_sub_image_3d(target, level, xoffset, yoffset, zoffset, width, height, depth, format, data, (uint32_t)imageSize);
}

void GL_APIENTRY glGenQueries(GLsizei n, GLuint * ids) {
    for (GLsizei i = 0; i < n; i++) ids[i] = gasm_gl_create_query();
}

void GL_APIENTRY glDeleteQueries(GLsizei n, const GLuint * ids) {
    for (GLsizei i = 0; i < n; i++) gasm_gl_delete_query(ids[i]);
}

GLboolean GL_APIENTRY glIsQuery(GLuint id) {
    return (GLboolean)gasm_gl_is_query(id);
}

void GL_APIENTRY glBeginQuery(GLenum target, GLuint id) {
    gasm_gl_begin_query(target, id);
}

void GL_APIENTRY glEndQuery(GLenum target) {
    gasm_gl_end_query(target);
}

void GL_APIENTRY glGetQueryiv(GLenum target, GLenum pname, GLint * params) {
    *params = gasm_gl_get_queryiv(target, pname);
}

void GL_APIENTRY glGetQueryObjectuiv(GLuint id, GLenum pname, GLuint * params) {
    *params = gasm_gl_get_query_objectuiv(id, pname);
}

GLboolean GL_APIENTRY glUnmapBuffer(GLenum target) {
    return unmap(target);
}

void GL_APIENTRY glGetBufferPointerv(GLenum target, GLenum pname, void ** params) {
    (void)pname;
    *params = mapping_for(target) ? mapping_for(target)->ptr : 0;
}

void GL_APIENTRY glDrawBuffers(GLsizei n, const GLenum * bufs) {
    gasm_gl_draw_buffers(bufs, (uint32_t)n);
}

void GL_APIENTRY glUniformMatrix2x3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) {
    gasm_gl_uniform_matrix2x3fv(location, count, transpose, value);
}

void GL_APIENTRY glUniformMatrix3x2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) {
    gasm_gl_uniform_matrix3x2fv(location, count, transpose, value);
}

void GL_APIENTRY glUniformMatrix2x4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) {
    gasm_gl_uniform_matrix2x4fv(location, count, transpose, value);
}

void GL_APIENTRY glUniformMatrix4x2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) {
    gasm_gl_uniform_matrix4x2fv(location, count, transpose, value);
}

void GL_APIENTRY glUniformMatrix3x4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) {
    gasm_gl_uniform_matrix3x4fv(location, count, transpose, value);
}

void GL_APIENTRY glUniformMatrix4x3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value) {
    gasm_gl_uniform_matrix4x3fv(location, count, transpose, value);
}

void GL_APIENTRY glBlitFramebuffer(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter) {
    gasm_gl_blit_framebuffer(srcX0, srcY0, srcX1, srcY1, dstX0, dstY0, dstX1, dstY1, mask, filter);
}

void GL_APIENTRY glRenderbufferStorageMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height) {
    gasm_gl_renderbuffer_storage_multisample(target, samples, internalformat, width, height);
}

void GL_APIENTRY glFramebufferTextureLayer(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer) {
    gasm_gl_framebuffer_texture_layer(target, attachment, texture, level, layer);
}

void * GL_APIENTRY glMapBufferRange(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access) {
    return map_range(target, offset, length, access);
}

void GL_APIENTRY glFlushMappedBufferRange(GLenum target, GLintptr offset, GLsizeiptr length) {
    flush_mapped(target, offset, length);
}

void GL_APIENTRY glBindVertexArray(GLuint array) {
    gasm_gl_bind_vertex_array(array);
}

void GL_APIENTRY glDeleteVertexArrays(GLsizei n, const GLuint * arrays) {
    for (GLsizei i = 0; i < n; i++) gasm_gl_delete_vertex_array(arrays[i]);
}

void GL_APIENTRY glGenVertexArrays(GLsizei n, GLuint * arrays) {
    for (GLsizei i = 0; i < n; i++) arrays[i] = gasm_gl_create_vertex_array();
}

GLboolean GL_APIENTRY glIsVertexArray(GLuint array) {
    return (GLboolean)gasm_gl_is_vertex_array(array);
}

void GL_APIENTRY glGetIntegeri_v(GLenum target, GLuint index, GLint * data) {
    gasm_gl_get_integeri_v(target, index, data, 16);
}

void GL_APIENTRY glBeginTransformFeedback(GLenum primitiveMode) {
    gasm_gl_begin_transform_feedback(primitiveMode);
}

void GL_APIENTRY glEndTransformFeedback(void) {
    gasm_gl_end_transform_feedback();
}

void GL_APIENTRY glBindBufferRange(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size) {
    gasm_gl_bind_buffer_range(target, index, buffer, offset, size);
}

void GL_APIENTRY glBindBufferBase(GLenum target, GLuint index, GLuint buffer) {
    gasm_gl_bind_buffer_base(target, index, buffer);
}

void GL_APIENTRY glTransformFeedbackVaryings(GLuint program, GLsizei count, const GLchar *const* varyings, GLenum bufferMode) {
    feedback_varyings(program, count, varyings, bufferMode);
}

void GL_APIENTRY glGetTransformFeedbackVarying(GLuint program, GLuint index, GLsizei bufSize, GLsizei * length, GLsizei * size, GLenum * type, GLchar * name) {
    active_info(gasm_gl_get_transform_feedback_varying, program, index, bufSize, length, size, type, name);
}

void GL_APIENTRY glVertexAttribIPointer(GLuint index, GLint size, GLenum type, GLsizei stride, const void * pointer) {
    gasm_gl_vertex_attrib_ipointer(index, size, type, stride, (uint32_t)(uintptr_t)pointer);
}

void GL_APIENTRY glGetVertexAttribIiv(GLuint index, GLenum pname, GLint * params) {
    *params = gasm_gl_get_vertex_attribiv(index, pname);
}

void GL_APIENTRY glGetVertexAttribIuiv(GLuint index, GLenum pname, GLuint * params) {
    *params = gasm_gl_get_vertex_attribiv(index, pname);
}

void GL_APIENTRY glVertexAttribI4i(GLuint index, GLint x, GLint y, GLint z, GLint w) {
    gasm_gl_vertex_attribi4i(index, x, y, z, w);
}

void GL_APIENTRY glVertexAttribI4ui(GLuint index, GLuint x, GLuint y, GLuint z, GLuint w) {
    gasm_gl_vertex_attribi4ui(index, x, y, z, w);
}

void GL_APIENTRY glVertexAttribI4iv(GLuint index, const GLint * v) {
    gasm_gl_vertex_attribi4i(index, v[0], v[1], v[2], v[3]);
}

void GL_APIENTRY glVertexAttribI4uiv(GLuint index, const GLuint * v) {
    gasm_gl_vertex_attribi4ui(index, v[0], v[1], v[2], v[3]);
}

void GL_APIENTRY glGetUniformuiv(GLuint program, GLint location, GLuint * params) {
    gasm_gl_get_uniformuiv(program, location, params, 16);
}

GLint GL_APIENTRY glGetFragDataLocation(GLuint program, const GLchar * name) {
    return gasm_gl_get_frag_data_location(program, name, (uint32_t)strlen(name));
}

void GL_APIENTRY glUniform1ui(GLint location, GLuint v0) {
    gasm_gl_uniform1ui(location, v0);
}

void GL_APIENTRY glUniform2ui(GLint location, GLuint v0, GLuint v1) {
    gasm_gl_uniform2ui(location, v0, v1);
}

void GL_APIENTRY glUniform3ui(GLint location, GLuint v0, GLuint v1, GLuint v2) {
    gasm_gl_uniform3ui(location, v0, v1, v2);
}

void GL_APIENTRY glUniform4ui(GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3) {
    gasm_gl_uniform4ui(location, v0, v1, v2, v3);
}

void GL_APIENTRY glUniform1uiv(GLint location, GLsizei count, const GLuint * value) {
    gasm_gl_uniform1uiv(location, count, value);
}

void GL_APIENTRY glUniform2uiv(GLint location, GLsizei count, const GLuint * value) {
    gasm_gl_uniform2uiv(location, count, value);
}

void GL_APIENTRY glUniform3uiv(GLint location, GLsizei count, const GLuint * value) {
    gasm_gl_uniform3uiv(location, count, value);
}

void GL_APIENTRY glUniform4uiv(GLint location, GLsizei count, const GLuint * value) {
    gasm_gl_uniform4uiv(location, count, value);
}

void GL_APIENTRY glClearBufferiv(GLenum buffer, GLint drawbuffer, const GLint * value) {
    gasm_gl_clear_bufferiv(buffer, drawbuffer, value, buffer == GL_COLOR ? 4 : 1);
}

void GL_APIENTRY glClearBufferuiv(GLenum buffer, GLint drawbuffer, const GLuint * value) {
    gasm_gl_clear_bufferuiv(buffer, drawbuffer, value, buffer == GL_COLOR ? 4 : 1);
}

void GL_APIENTRY glClearBufferfv(GLenum buffer, GLint drawbuffer, const GLfloat * value) {
    gasm_gl_clear_bufferfv(buffer, drawbuffer, value, buffer == GL_COLOR ? 4 : 1);
}

void GL_APIENTRY glClearBufferfi(GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil) {
    gasm_gl_clear_bufferfi(buffer, drawbuffer, depth, stencil);
}

const GLubyte * GL_APIENTRY glGetStringi(GLenum name, GLuint index) {
    return name == GL_EXTENSIONS ? extension(index) : (c_error = GL_INVALID_ENUM, (const GLubyte *)0);
}

void GL_APIENTRY glCopyBufferSubData(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size) {
    gasm_gl_copy_buffer_sub_data(readTarget, writeTarget, readOffset, writeOffset, size);
}

void GL_APIENTRY glGetUniformIndices(GLuint program, GLsizei uniformCount, const GLchar *const* uniformNames, GLuint * uniformIndices) {
    for (GLsizei i = 0; i < uniformCount; i++) uniformIndices[i] = gasm_gl_get_uniform_index(program, uniformNames[i], (uint32_t)strlen(uniformNames[i]));
}

void GL_APIENTRY glGetActiveUniformsiv(GLuint program, GLsizei uniformCount, const GLuint * uniformIndices, GLenum pname, GLint * params) {
    gasm_gl_get_active_uniformsiv(program, uniformIndices, (uint32_t)uniformCount, pname, params);
}

GLuint GL_APIENTRY glGetUniformBlockIndex(GLuint program, const GLchar * uniformBlockName) {
    return gasm_gl_get_uniform_block_index(program, uniformBlockName, (uint32_t)strlen(uniformBlockName));
}

void GL_APIENTRY glGetActiveUniformBlockiv(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint * params) {
    gasm_gl_get_active_uniform_blockiv(program, uniformBlockIndex, pname, params, 64);
}

void GL_APIENTRY glGetActiveUniformBlockName(GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei * length, GLchar * uniformBlockName) {
    truncated2(gasm_gl_get_active_uniform_block_name, program, uniformBlockIndex, bufSize, length, uniformBlockName);
}

void GL_APIENTRY glUniformBlockBinding(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding) {
    gasm_gl_uniform_block_binding(program, uniformBlockIndex, uniformBlockBinding);
}

void GL_APIENTRY glDrawArraysInstanced(GLenum mode, GLint first, GLsizei count, GLsizei instancecount) {
    gasm_gl_draw_arrays_instanced(mode, first, count, instancecount);
}

void GL_APIENTRY glDrawElementsInstanced(GLenum mode, GLsizei count, GLenum type, const void * indices, GLsizei instancecount) {
    gasm_gl_draw_elements_instanced(mode, count, type, (uint32_t)(uintptr_t)indices, instancecount);
}

GLsync GL_APIENTRY glFenceSync(GLenum condition, GLbitfield flags) {
    return (GLsync)(uintptr_t)gasm_gl_fence_sync(condition, flags);
}

GLboolean GL_APIENTRY glIsSync(GLsync sync) {
    return (GLboolean)gasm_gl_is_sync((uint32_t)(uintptr_t)sync);
}

void GL_APIENTRY glDeleteSync(GLsync sync) {
    gasm_gl_delete_sync((uint32_t)(uintptr_t)sync);
}

GLenum GL_APIENTRY glClientWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout) {
    return gasm_gl_client_wait_sync((uint32_t)(uintptr_t)sync, flags, timeout);
}

void GL_APIENTRY glWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout) {
    gasm_gl_wait_sync((uint32_t)(uintptr_t)sync, flags, timeout);
}

void GL_APIENTRY glGetInteger64v(GLenum pname, GLint64 * data) {
    gasm_gl_get_integer64v(pname, data, 64);
}

void GL_APIENTRY glGetSynciv(GLsync sync, GLenum pname, GLsizei bufSize, GLsizei * length, GLint * values) {
    if (bufSize > 0) values[0] = gasm_gl_get_synciv((uint32_t)(uintptr_t)sync, pname);
    if (length) *length = bufSize > 0 ? 1 : 0;
}

void GL_APIENTRY glGetInteger64i_v(GLenum target, GLuint index, GLint64 * data) {
    GLint v[16];
    int n = gasm_gl_get_integeri_v(target, index, v, 16);
    for (int i = 0; i < n && i < 16; i++) data[i] = v[i];
}

void GL_APIENTRY glGetBufferParameteri64v(GLenum target, GLenum pname, GLint64 * params) {
    *params = gasm_gl_get_buffer_parameteriv(target, pname);
}

void GL_APIENTRY glGenSamplers(GLsizei count, GLuint * samplers) {
    for (GLsizei i = 0; i < count; i++) samplers[i] = gasm_gl_create_sampler();
}

void GL_APIENTRY glDeleteSamplers(GLsizei count, const GLuint * samplers) {
    for (GLsizei i = 0; i < count; i++) gasm_gl_delete_sampler(samplers[i]);
}

GLboolean GL_APIENTRY glIsSampler(GLuint sampler) {
    return (GLboolean)gasm_gl_is_sampler(sampler);
}

void GL_APIENTRY glBindSampler(GLuint unit, GLuint sampler) {
    gasm_gl_bind_sampler(unit, sampler);
}

void GL_APIENTRY glSamplerParameteri(GLuint sampler, GLenum pname, GLint param) {
    gasm_gl_sampler_parameteri(sampler, pname, param);
}

void GL_APIENTRY glSamplerParameteriv(GLuint sampler, GLenum pname, const GLint * param) {
    gasm_gl_sampler_parameteri(sampler, pname, param[0]);
}

void GL_APIENTRY glSamplerParameterf(GLuint sampler, GLenum pname, GLfloat param) {
    gasm_gl_sampler_parameterf(sampler, pname, param);
}

void GL_APIENTRY glSamplerParameterfv(GLuint sampler, GLenum pname, const GLfloat * param) {
    gasm_gl_sampler_parameterf(sampler, pname, param[0]);
}

void GL_APIENTRY glGetSamplerParameteriv(GLuint sampler, GLenum pname, GLint * params) {
    *params = gasm_gl_get_sampler_parameteriv(sampler, pname);
}

void GL_APIENTRY glGetSamplerParameterfv(GLuint sampler, GLenum pname, GLfloat * params) {
    *params = gasm_gl_get_sampler_parameterfv(sampler, pname);
}

void GL_APIENTRY glVertexAttribDivisor(GLuint index, GLuint divisor) {
    gasm_gl_vertex_attrib_divisor(index, divisor);
}

void GL_APIENTRY glBindTransformFeedback(GLenum target, GLuint id) {
    gasm_gl_bind_transform_feedback(target, id);
}

void GL_APIENTRY glDeleteTransformFeedbacks(GLsizei n, const GLuint * ids) {
    for (GLsizei i = 0; i < n; i++) gasm_gl_delete_transform_feedback(ids[i]);
}

void GL_APIENTRY glGenTransformFeedbacks(GLsizei n, GLuint * ids) {
    for (GLsizei i = 0; i < n; i++) ids[i] = gasm_gl_create_transform_feedback();
}

GLboolean GL_APIENTRY glIsTransformFeedback(GLuint id) {
    return (GLboolean)gasm_gl_is_transform_feedback(id);
}

void GL_APIENTRY glPauseTransformFeedback(void) {
    gasm_gl_pause_transform_feedback();
}

void GL_APIENTRY glResumeTransformFeedback(void) {
    gasm_gl_resume_transform_feedback();
}

void GL_APIENTRY glGetProgramBinary(GLuint program, GLsizei bufSize, GLsizei * length, GLenum * binaryFormat, void * binary) {
    (void)program;
    (void)bufSize;
    (void)binaryFormat;
    (void)binary;
    if (length) *length = 0;
    c_error = GL_INVALID_OPERATION;
}

void GL_APIENTRY glProgramBinary(GLuint program, GLenum binaryFormat, const void * binary, GLsizei length) {
    (void)program;
    (void)binaryFormat;
    (void)binary;
    (void)length;
    c_error = GL_INVALID_ENUM;
}

void GL_APIENTRY glProgramParameteri(GLuint program, GLenum pname, GLint value) {
    (void)program;
    (void)pname;
    (void)value;
}

void GL_APIENTRY glInvalidateFramebuffer(GLenum target, GLsizei numAttachments, const GLenum * attachments) {
    gasm_gl_invalidate_framebuffer(target, attachments, (uint32_t)numAttachments);
}

void GL_APIENTRY glInvalidateSubFramebuffer(GLenum target, GLsizei numAttachments, const GLenum * attachments, GLint x, GLint y, GLsizei width, GLsizei height) {
    gasm_gl_invalidate_sub_framebuffer(target, attachments, (uint32_t)numAttachments, x, y, width, height);
}

void GL_APIENTRY glTexStorage2D(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height) {
    gasm_gl_tex_storage_2d(target, levels, internalformat, width, height);
}

void GL_APIENTRY glTexStorage3D(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth) {
    gasm_gl_tex_storage_3d(target, levels, internalformat, width, height, depth);
}

void GL_APIENTRY glGetInternalformativ(GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint * params) {
    gasm_gl_get_internalformativ(target, internalformat, pname, params, (uint32_t)bufSize);
}
