/*
 * ScummVM on gasm: engine data files built into the module (sky.cpt, ...), so
 * players only provide the game itself. The table is generated by
 * scripts/embed-files.mjs (gasm-data.cpp); GasmEmbeddedArchive serves it.
 *
 * SPDX-License-Identifier: MIT (this file; the ScummVM build as a whole is GPL-3.0)
 */
#ifndef BACKENDS_PLATFORM_GASM_DATA_H
#define BACKENDS_PLATFORM_GASM_DATA_H

struct GasmEmbeddedFile {
	const char *name;
	const unsigned char *data;
	unsigned size;
};

extern const GasmEmbeddedFile gasmEmbeddedFiles[];
extern const unsigned gasmEmbeddedCount;

#ifdef __cplusplus
#include "common/archive.h"

/** The embedded files as an archive for the search set. */
class GasmEmbeddedArchive : public Common::Archive {
public:
	bool hasFile(const Common::Path &path) const override;
	int listMembers(Common::ArchiveMemberList &list) const override;
	const Common::ArchiveMemberPtr getMember(const Common::Path &path) const override;
	Common::SeekableReadStream *createReadStreamForMember(const Common::Path &path) const override;
private:
	const GasmEmbeddedFile *find(const Common::Path &path) const;
};
#endif

#endif
