/* Generated by scripts/gen-gl-headers.py from the Khronos registry (gl.xml) and spec/abi.json: do not edit. */
#ifndef __khrplatform_h_
#define __khrplatform_h_
#include <stdint.h>
typedef int32_t khronos_int32_t;
typedef uint32_t khronos_uint32_t;
typedef int64_t khronos_int64_t;
typedef uint64_t khronos_uint64_t;
typedef float khronos_float_t;
typedef long khronos_intptr_t;
typedef long khronos_ssize_t;
#define KHRONOS_APICALL
#define KHRONOS_APIENTRY
#endif
