/* Generated by scripts/gen-gl-headers.py from the Khronos registry (gl.xml) and spec/abi.json: do not edit. */
/* GLES 2 code builds against the GLES 3.0 header (a superset). */
#include <GLES3/gl3.h>
