#!/usr/bin/env node
// Embed files in a C++ source: node scripts/embed-files.mjs out.cpp name=path ...
// Produces `gasmEmbeddedFiles[]` / `gasmEmbeddedCount` (see guests/scummvm/backend/gasm-data.h).
import { readFileSync, writeFileSync } from 'node:fs';
const [out, ...items] = process.argv.slice(2);
const lines = ['// GENERATED by scripts/embed-files.mjs. Do not edit.', '#include "backends/platform/gasm/gasm-data.h"', ''];
const table = [];
items.forEach((item, i) => {
  const k = item.indexOf('=');
  const name = item.slice(0, k), bytes = readFileSync(item.slice(k + 1));
  lines.push(`static const unsigned char file${i}[] = {`);
  for (let o = 0; o < bytes.length; o += 32) lines.push('\t' + [...bytes.subarray(o, o + 32)].join(',') + ',');
  lines.push('};');
  table.push(`\t{ ${JSON.stringify(name)}, file${i}, ${bytes.length}u },`);
});
lines.push('', 'const GasmEmbeddedFile gasmEmbeddedFiles[] = {', ...table, '\t{ nullptr, nullptr, 0 },', '};');
lines.push(`const unsigned gasmEmbeddedCount = ${items.length};`, '');
writeFileSync(out, lines.join('\n'));
console.log(`embedded ${items.length} files into ${out}`);
