#!/usr/bin/env bash
# Fetch ScummVM (GPL-3.0) into tools/scummvm-src (git-ignored), add gasm's backend
# (guests/scummvm/backend -> backends/platform/gasm) and patch configure for the
# wasm32-gasm host. guests/scummvm holds only gasm's own files.
#
# Incremental: the tarball is fetched once per version, configure is re-patched only
# when configure.patch changes (.gasm-configure records it), and backend files are
# copied only when they differ, so an edit recompiles just that file.
set -euo pipefail
cd "$(dirname "$0")/.."
. scripts/lib.sh
VERSION=2026.3.0
SHA256=54ec34519be9edb24f952afda9deb9a49d5ace35c3539feaa654a09fb08ce81a
OUT=tools/scummvm-src
if [ ! -f "$OUT/.pristine-$VERSION" ]; then
  echo "fetching scummvm $VERSION"
  rm -rf "$OUT" && mkdir -p tools
  TMP=$(mktemp -d)
  trap 'rm -rf "$TMP"' EXIT
  download "https://github.com/scummvm/scummvm/archive/refs/tags/v$VERSION.tar.gz" "$TMP/scummvm.tar.gz" "$SHA256"
  tar xzf "$TMP/scummvm.tar.gz" -C "$TMP"
  mv "$TMP/scummvm-$VERSION" "$OUT"
  cp "$OUT/configure" "$OUT/.configure.orig"
  touch "$OUT/.pristine-$VERSION"
fi

# configure patch (re-applied from the pristine configure when the patch changes)
SIG="$VERSION $(cksum < guests/scummvm/configure.patch | cut -d' ' -f1)"
if [ ! -f "$OUT/.gasm-configure" ] || [ "$(cat "$OUT/.gasm-configure")" != "$SIG" ]; then
  cp "$OUT/.configure.orig" "$OUT/configure"
  patch -s -p1 -d "$OUT" < guests/scummvm/configure.patch
  echo "$SIG" > "$OUT/.gasm-configure"
fi

# backend files, plus the frame loop helper from the C SDK (compiled as C++ there)
DST="$OUT/backends/platform/gasm"
mkdir -p "$DST"
sync_file() { # <src> <dst>: copy only if different (keeps the mtime of unchanged files)
  cmp -s "$1" "$2" || cp "$1" "$2"
}
want=" gasm-loop.cpp gasm_loop.h gasm-data.cpp "
for f in guests/scummvm/backend/*; do
  sync_file "$f" "$DST/$(basename "$f")"
  want="$want$(basename "$f") "
done
sync_file sdk/c/src/gasm_loop.c "$DST/gasm-loop.cpp"
sync_file sdk/c/include/gasm_loop.h "$DST/gasm_loop.h"
# drop files that are no longer in the backend (gasm-data.cpp is generated by make)
for f in "$DST"/*; do
  case "$want" in *" $(basename "$f") "*) ;; *) rm -f "$f" ;; esac
done
