// The GLES 3.0 functions that forward one to one to gasm:gl, the type of every
// function, and the name table.
// GENERATED by scripts/gen-gl-headers.py from gl.xml and spec/abi.json: do not edit.

pub unsafe extern "C" fn glActiveTexture(p0: u32) {
    unsafe { crate::sys::gl_active_texture(p0 as _) }
}
pub unsafe extern "C" fn glAttachShader(p0: u32, p1: u32) {
    unsafe { crate::sys::gl_attach_shader(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glBindFramebuffer(p0: u32, p1: u32) {
    unsafe { crate::sys::gl_bind_framebuffer(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glBindRenderbuffer(p0: u32, p1: u32) {
    unsafe { crate::sys::gl_bind_renderbuffer(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glBindTexture(p0: u32, p1: u32) {
    unsafe { crate::sys::gl_bind_texture(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glBlendColor(p0: f32, p1: f32, p2: f32, p3: f32) {
    unsafe { crate::sys::gl_blend_color(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glBlendEquation(p0: u32) {
    unsafe { crate::sys::gl_blend_equation(p0 as _) }
}
pub unsafe extern "C" fn glBlendEquationSeparate(p0: u32, p1: u32) {
    unsafe { crate::sys::gl_blend_equation_separate(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glBlendFunc(p0: u32, p1: u32) {
    unsafe { crate::sys::gl_blend_func(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glBlendFuncSeparate(p0: u32, p1: u32, p2: u32, p3: u32) {
    unsafe { crate::sys::gl_blend_func_separate(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glCheckFramebufferStatus(p0: u32) -> u32 {
    unsafe { crate::sys::gl_check_framebuffer_status(p0 as _) as _ }
}
pub unsafe extern "C" fn glClear(p0: u32) {
    unsafe { crate::sys::gl_clear(p0 as _) }
}
pub unsafe extern "C" fn glClearColor(p0: f32, p1: f32, p2: f32, p3: f32) {
    unsafe { crate::sys::gl_clear_color(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glClearDepthf(p0: f32) {
    unsafe { crate::sys::gl_clear_depthf(p0 as _) }
}
pub unsafe extern "C" fn glClearStencil(p0: i32) {
    unsafe { crate::sys::gl_clear_stencil(p0 as _) }
}
pub unsafe extern "C" fn glColorMask(p0: u8, p1: u8, p2: u8, p3: u8) {
    unsafe { crate::sys::gl_color_mask(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glCompileShader(p0: u32) {
    unsafe { crate::sys::gl_compile_shader(p0 as _) }
}
pub unsafe extern "C" fn glCopyTexImage2D(p0: u32, p1: i32, p2: u32, p3: i32, p4: i32, p5: i32, p6: i32, p7: i32) {
    unsafe { crate::sys::gl_copy_tex_image_2d(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _, p5 as _, p6 as _, p7 as _) }
}
pub unsafe extern "C" fn glCopyTexSubImage2D(p0: u32, p1: i32, p2: i32, p3: i32, p4: i32, p5: i32, p6: i32, p7: i32) {
    unsafe { crate::sys::gl_copy_tex_sub_image_2d(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _, p5 as _, p6 as _, p7 as _) }
}
pub unsafe extern "C" fn glCreateProgram() -> u32 {
    unsafe { crate::sys::gl_create_program() as _ }
}
pub unsafe extern "C" fn glCreateShader(p0: u32) -> u32 {
    unsafe { crate::sys::gl_create_shader(p0 as _) as _ }
}
pub unsafe extern "C" fn glCullFace(p0: u32) {
    unsafe { crate::sys::gl_cull_face(p0 as _) }
}
pub unsafe extern "C" fn glDeleteProgram(p0: u32) {
    unsafe { crate::sys::gl_delete_program(p0 as _) }
}
pub unsafe extern "C" fn glDeleteShader(p0: u32) {
    unsafe { crate::sys::gl_delete_shader(p0 as _) }
}
pub unsafe extern "C" fn glDepthFunc(p0: u32) {
    unsafe { crate::sys::gl_depth_func(p0 as _) }
}
pub unsafe extern "C" fn glDepthMask(p0: u8) {
    unsafe { crate::sys::gl_depth_mask(p0 as _) }
}
pub unsafe extern "C" fn glDepthRangef(p0: f32, p1: f32) {
    unsafe { crate::sys::gl_depth_rangef(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glDetachShader(p0: u32, p1: u32) {
    unsafe { crate::sys::gl_detach_shader(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glDisable(p0: u32) {
    unsafe { crate::sys::gl_disable(p0 as _) }
}
pub unsafe extern "C" fn glDisableVertexAttribArray(p0: u32) {
    unsafe { crate::sys::gl_disable_vertex_attrib_array(p0 as _) }
}
pub unsafe extern "C" fn glDrawArrays(p0: u32, p1: i32, p2: i32) {
    unsafe { crate::sys::gl_draw_arrays(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glEnable(p0: u32) {
    unsafe { crate::sys::gl_enable(p0 as _) }
}
pub unsafe extern "C" fn glEnableVertexAttribArray(p0: u32) {
    unsafe { crate::sys::gl_enable_vertex_attrib_array(p0 as _) }
}
pub unsafe extern "C" fn glFinish() {
    unsafe { crate::sys::gl_finish() }
}
pub unsafe extern "C" fn glFlush() {
    unsafe { crate::sys::gl_flush() }
}
pub unsafe extern "C" fn glFramebufferRenderbuffer(p0: u32, p1: u32, p2: u32, p3: u32) {
    unsafe { crate::sys::gl_framebuffer_renderbuffer(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glFramebufferTexture2D(p0: u32, p1: u32, p2: u32, p3: u32, p4: i32) {
    unsafe { crate::sys::gl_framebuffer_texture_2d(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _) }
}
pub unsafe extern "C" fn glFrontFace(p0: u32) {
    unsafe { crate::sys::gl_front_face(p0 as _) }
}
pub unsafe extern "C" fn glGenerateMipmap(p0: u32) {
    unsafe { crate::sys::gl_generate_mipmap(p0 as _) }
}
pub unsafe extern "C" fn glHint(p0: u32, p1: u32) {
    unsafe { crate::sys::gl_hint(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glIsBuffer(p0: u32) -> u8 {
    unsafe { crate::sys::gl_is_buffer(p0 as _) as _ }
}
pub unsafe extern "C" fn glIsEnabled(p0: u32) -> u8 {
    unsafe { crate::sys::gl_is_enabled(p0 as _) as _ }
}
pub unsafe extern "C" fn glIsFramebuffer(p0: u32) -> u8 {
    unsafe { crate::sys::gl_is_framebuffer(p0 as _) as _ }
}
pub unsafe extern "C" fn glIsProgram(p0: u32) -> u8 {
    unsafe { crate::sys::gl_is_program(p0 as _) as _ }
}
pub unsafe extern "C" fn glIsRenderbuffer(p0: u32) -> u8 {
    unsafe { crate::sys::gl_is_renderbuffer(p0 as _) as _ }
}
pub unsafe extern "C" fn glIsShader(p0: u32) -> u8 {
    unsafe { crate::sys::gl_is_shader(p0 as _) as _ }
}
pub unsafe extern "C" fn glIsTexture(p0: u32) -> u8 {
    unsafe { crate::sys::gl_is_texture(p0 as _) as _ }
}
pub unsafe extern "C" fn glLineWidth(p0: f32) {
    unsafe { crate::sys::gl_line_width(p0 as _) }
}
pub unsafe extern "C" fn glLinkProgram(p0: u32) {
    unsafe { crate::sys::gl_link_program(p0 as _) }
}
pub unsafe extern "C" fn glPolygonOffset(p0: f32, p1: f32) {
    unsafe { crate::sys::gl_polygon_offset(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glRenderbufferStorage(p0: u32, p1: u32, p2: i32, p3: i32) {
    unsafe { crate::sys::gl_renderbuffer_storage(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glSampleCoverage(p0: f32, p1: u8) {
    unsafe { crate::sys::gl_sample_coverage(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glScissor(p0: i32, p1: i32, p2: i32, p3: i32) {
    unsafe { crate::sys::gl_scissor(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glStencilFunc(p0: u32, p1: i32, p2: u32) {
    unsafe { crate::sys::gl_stencil_func(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glStencilFuncSeparate(p0: u32, p1: u32, p2: i32, p3: u32) {
    unsafe { crate::sys::gl_stencil_func_separate(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glStencilMask(p0: u32) {
    unsafe { crate::sys::gl_stencil_mask(p0 as _) }
}
pub unsafe extern "C" fn glStencilMaskSeparate(p0: u32, p1: u32) {
    unsafe { crate::sys::gl_stencil_mask_separate(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glStencilOp(p0: u32, p1: u32, p2: u32) {
    unsafe { crate::sys::gl_stencil_op(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glStencilOpSeparate(p0: u32, p1: u32, p2: u32, p3: u32) {
    unsafe { crate::sys::gl_stencil_op_separate(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glTexParameterf(p0: u32, p1: u32, p2: f32) {
    unsafe { crate::sys::gl_tex_parameterf(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glTexParameteri(p0: u32, p1: u32, p2: i32) {
    unsafe { crate::sys::gl_tex_parameteri(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glUniform1f(p0: i32, p1: f32) {
    unsafe { crate::sys::gl_uniform1f(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glUniform1fv(p0: i32, p1: i32, p2: *const c_void) {
    unsafe { crate::sys::gl_uniform1fv(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glUniform1i(p0: i32, p1: i32) {
    unsafe { crate::sys::gl_uniform1i(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glUniform1iv(p0: i32, p1: i32, p2: *const c_void) {
    unsafe { crate::sys::gl_uniform1iv(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glUniform2f(p0: i32, p1: f32, p2: f32) {
    unsafe { crate::sys::gl_uniform2f(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glUniform2fv(p0: i32, p1: i32, p2: *const c_void) {
    unsafe { crate::sys::gl_uniform2fv(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glUniform2i(p0: i32, p1: i32, p2: i32) {
    unsafe { crate::sys::gl_uniform2i(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glUniform2iv(p0: i32, p1: i32, p2: *const c_void) {
    unsafe { crate::sys::gl_uniform2iv(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glUniform3f(p0: i32, p1: f32, p2: f32, p3: f32) {
    unsafe { crate::sys::gl_uniform3f(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glUniform3fv(p0: i32, p1: i32, p2: *const c_void) {
    unsafe { crate::sys::gl_uniform3fv(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glUniform3i(p0: i32, p1: i32, p2: i32, p3: i32) {
    unsafe { crate::sys::gl_uniform3i(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glUniform3iv(p0: i32, p1: i32, p2: *const c_void) {
    unsafe { crate::sys::gl_uniform3iv(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glUniform4f(p0: i32, p1: f32, p2: f32, p3: f32, p4: f32) {
    unsafe { crate::sys::gl_uniform4f(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _) }
}
pub unsafe extern "C" fn glUniform4fv(p0: i32, p1: i32, p2: *const c_void) {
    unsafe { crate::sys::gl_uniform4fv(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glUniform4i(p0: i32, p1: i32, p2: i32, p3: i32, p4: i32) {
    unsafe { crate::sys::gl_uniform4i(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _) }
}
pub unsafe extern "C" fn glUniform4iv(p0: i32, p1: i32, p2: *const c_void) {
    unsafe { crate::sys::gl_uniform4iv(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glUniformMatrix2fv(p0: i32, p1: i32, p2: u8, p3: *const c_void) {
    unsafe { crate::sys::gl_uniform_matrix2fv(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glUniformMatrix3fv(p0: i32, p1: i32, p2: u8, p3: *const c_void) {
    unsafe { crate::sys::gl_uniform_matrix3fv(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glUniformMatrix4fv(p0: i32, p1: i32, p2: u8, p3: *const c_void) {
    unsafe { crate::sys::gl_uniform_matrix4fv(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glUseProgram(p0: u32) {
    unsafe { crate::sys::gl_use_program(p0 as _) }
}
pub unsafe extern "C" fn glValidateProgram(p0: u32) {
    unsafe { crate::sys::gl_validate_program(p0 as _) }
}
pub unsafe extern "C" fn glVertexAttrib4f(p0: u32, p1: f32, p2: f32, p3: f32, p4: f32) {
    unsafe { crate::sys::gl_vertex_attrib4f(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _) }
}
pub unsafe extern "C" fn glViewport(p0: i32, p1: i32, p2: i32, p3: i32) {
    unsafe { crate::sys::gl_viewport(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glReadBuffer(p0: u32) {
    unsafe { crate::sys::gl_read_buffer(p0 as _) }
}
pub unsafe extern "C" fn glCopyTexSubImage3D(p0: u32, p1: i32, p2: i32, p3: i32, p4: i32, p5: i32, p6: i32, p7: i32, p8: i32) {
    unsafe { crate::sys::gl_copy_tex_sub_image_3d(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _, p5 as _, p6 as _, p7 as _, p8 as _) }
}
pub unsafe extern "C" fn glIsQuery(p0: u32) -> u8 {
    unsafe { crate::sys::gl_is_query(p0 as _) as _ }
}
pub unsafe extern "C" fn glBeginQuery(p0: u32, p1: u32) {
    unsafe { crate::sys::gl_begin_query(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glEndQuery(p0: u32) {
    unsafe { crate::sys::gl_end_query(p0 as _) }
}
pub unsafe extern "C" fn glUniformMatrix2x3fv(p0: i32, p1: i32, p2: u8, p3: *const c_void) {
    unsafe { crate::sys::gl_uniform_matrix2x3fv(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glUniformMatrix3x2fv(p0: i32, p1: i32, p2: u8, p3: *const c_void) {
    unsafe { crate::sys::gl_uniform_matrix3x2fv(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glUniformMatrix2x4fv(p0: i32, p1: i32, p2: u8, p3: *const c_void) {
    unsafe { crate::sys::gl_uniform_matrix2x4fv(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glUniformMatrix4x2fv(p0: i32, p1: i32, p2: u8, p3: *const c_void) {
    unsafe { crate::sys::gl_uniform_matrix4x2fv(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glUniformMatrix3x4fv(p0: i32, p1: i32, p2: u8, p3: *const c_void) {
    unsafe { crate::sys::gl_uniform_matrix3x4fv(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glUniformMatrix4x3fv(p0: i32, p1: i32, p2: u8, p3: *const c_void) {
    unsafe { crate::sys::gl_uniform_matrix4x3fv(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glBlitFramebuffer(p0: i32, p1: i32, p2: i32, p3: i32, p4: i32, p5: i32, p6: i32, p7: i32, p8: u32, p9: u32) {
    unsafe { crate::sys::gl_blit_framebuffer(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _, p5 as _, p6 as _, p7 as _, p8 as _, p9 as _) }
}
pub unsafe extern "C" fn glRenderbufferStorageMultisample(p0: u32, p1: i32, p2: u32, p3: i32, p4: i32) {
    unsafe { crate::sys::gl_renderbuffer_storage_multisample(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _) }
}
pub unsafe extern "C" fn glFramebufferTextureLayer(p0: u32, p1: u32, p2: u32, p3: i32, p4: i32) {
    unsafe { crate::sys::gl_framebuffer_texture_layer(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _) }
}
pub unsafe extern "C" fn glBindVertexArray(p0: u32) {
    unsafe { crate::sys::gl_bind_vertex_array(p0 as _) }
}
pub unsafe extern "C" fn glIsVertexArray(p0: u32) -> u8 {
    unsafe { crate::sys::gl_is_vertex_array(p0 as _) as _ }
}
pub unsafe extern "C" fn glBeginTransformFeedback(p0: u32) {
    unsafe { crate::sys::gl_begin_transform_feedback(p0 as _) }
}
pub unsafe extern "C" fn glEndTransformFeedback() {
    unsafe { crate::sys::gl_end_transform_feedback() }
}
pub unsafe extern "C" fn glBindBufferRange(p0: u32, p1: u32, p2: u32, p3: isize, p4: isize) {
    unsafe { crate::sys::gl_bind_buffer_range(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _) }
}
pub unsafe extern "C" fn glBindBufferBase(p0: u32, p1: u32, p2: u32) {
    unsafe { crate::sys::gl_bind_buffer_base(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glVertexAttribI4i(p0: u32, p1: i32, p2: i32, p3: i32, p4: i32) {
    unsafe { crate::sys::gl_vertex_attribi4i(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _) }
}
pub unsafe extern "C" fn glVertexAttribI4ui(p0: u32, p1: u32, p2: u32, p3: u32, p4: u32) {
    unsafe { crate::sys::gl_vertex_attribi4ui(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _) }
}
pub unsafe extern "C" fn glUniform1ui(p0: i32, p1: u32) {
    unsafe { crate::sys::gl_uniform1ui(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glUniform2ui(p0: i32, p1: u32, p2: u32) {
    unsafe { crate::sys::gl_uniform2ui(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glUniform3ui(p0: i32, p1: u32, p2: u32, p3: u32) {
    unsafe { crate::sys::gl_uniform3ui(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glUniform4ui(p0: i32, p1: u32, p2: u32, p3: u32, p4: u32) {
    unsafe { crate::sys::gl_uniform4ui(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _) }
}
pub unsafe extern "C" fn glUniform1uiv(p0: i32, p1: i32, p2: *const c_void) {
    unsafe { crate::sys::gl_uniform1uiv(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glUniform2uiv(p0: i32, p1: i32, p2: *const c_void) {
    unsafe { crate::sys::gl_uniform2uiv(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glUniform3uiv(p0: i32, p1: i32, p2: *const c_void) {
    unsafe { crate::sys::gl_uniform3uiv(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glUniform4uiv(p0: i32, p1: i32, p2: *const c_void) {
    unsafe { crate::sys::gl_uniform4uiv(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glClearBufferfi(p0: u32, p1: i32, p2: f32, p3: i32) {
    unsafe { crate::sys::gl_clear_bufferfi(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glCopyBufferSubData(p0: u32, p1: u32, p2: isize, p3: isize, p4: isize) {
    unsafe { crate::sys::gl_copy_buffer_sub_data(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _) }
}
pub unsafe extern "C" fn glUniformBlockBinding(p0: u32, p1: u32, p2: u32) {
    unsafe { crate::sys::gl_uniform_block_binding(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glDrawArraysInstanced(p0: u32, p1: i32, p2: i32, p3: i32) {
    unsafe { crate::sys::gl_draw_arrays_instanced(p0 as _, p1 as _, p2 as _, p3 as _) }
}
pub unsafe extern "C" fn glIsSampler(p0: u32) -> u8 {
    unsafe { crate::sys::gl_is_sampler(p0 as _) as _ }
}
pub unsafe extern "C" fn glBindSampler(p0: u32, p1: u32) {
    unsafe { crate::sys::gl_bind_sampler(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glSamplerParameteri(p0: u32, p1: u32, p2: i32) {
    unsafe { crate::sys::gl_sampler_parameteri(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glSamplerParameterf(p0: u32, p1: u32, p2: f32) {
    unsafe { crate::sys::gl_sampler_parameterf(p0 as _, p1 as _, p2 as _) }
}
pub unsafe extern "C" fn glVertexAttribDivisor(p0: u32, p1: u32) {
    unsafe { crate::sys::gl_vertex_attrib_divisor(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glBindTransformFeedback(p0: u32, p1: u32) {
    unsafe { crate::sys::gl_bind_transform_feedback(p0 as _, p1 as _) }
}
pub unsafe extern "C" fn glIsTransformFeedback(p0: u32) -> u8 {
    unsafe { crate::sys::gl_is_transform_feedback(p0 as _) as _ }
}
pub unsafe extern "C" fn glPauseTransformFeedback() {
    unsafe { crate::sys::gl_pause_transform_feedback() }
}
pub unsafe extern "C" fn glResumeTransformFeedback() {
    unsafe { crate::sys::gl_resume_transform_feedback() }
}
pub unsafe extern "C" fn glTexStorage2D(p0: u32, p1: i32, p2: u32, p3: i32, p4: i32) {
    unsafe { crate::sys::gl_tex_storage_2d(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _) }
}
pub unsafe extern "C" fn glTexStorage3D(p0: u32, p1: i32, p2: u32, p3: i32, p4: i32, p5: i32) {
    unsafe { crate::sys::gl_tex_storage_3d(p0 as _, p1 as _, p2 as _, p3 as _, p4 as _, p5 as _) }
}

// every function has the C signature of gl.xml (glow calls them through pointers)
const _: () = {
    let _: unsafe extern "C" fn(u32) = glActiveTexture;
    let _: unsafe extern "C" fn(u32, u32) = glAttachShader;
    let _: unsafe extern "C" fn(u32, u32, *const c_void) = glBindAttribLocation;
    let _: unsafe extern "C" fn(u32, u32) = glBindBuffer;
    let _: unsafe extern "C" fn(u32, u32) = glBindFramebuffer;
    let _: unsafe extern "C" fn(u32, u32) = glBindRenderbuffer;
    let _: unsafe extern "C" fn(u32, u32) = glBindTexture;
    let _: unsafe extern "C" fn(f32, f32, f32, f32) = glBlendColor;
    let _: unsafe extern "C" fn(u32) = glBlendEquation;
    let _: unsafe extern "C" fn(u32, u32) = glBlendEquationSeparate;
    let _: unsafe extern "C" fn(u32, u32) = glBlendFunc;
    let _: unsafe extern "C" fn(u32, u32, u32, u32) = glBlendFuncSeparate;
    let _: unsafe extern "C" fn(u32, isize, *const c_void, u32) = glBufferData;
    let _: unsafe extern "C" fn(u32, isize, isize, *const c_void) = glBufferSubData;
    let _: unsafe extern "C" fn(u32) -> u32 = glCheckFramebufferStatus;
    let _: unsafe extern "C" fn(u32) = glClear;
    let _: unsafe extern "C" fn(f32, f32, f32, f32) = glClearColor;
    let _: unsafe extern "C" fn(f32) = glClearDepthf;
    let _: unsafe extern "C" fn(i32) = glClearStencil;
    let _: unsafe extern "C" fn(u8, u8, u8, u8) = glColorMask;
    let _: unsafe extern "C" fn(u32) = glCompileShader;
    let _: unsafe extern "C" fn(u32, i32, u32, i32, i32, i32, i32, *const c_void) = glCompressedTexImage2D;
    let _: unsafe extern "C" fn(u32, i32, i32, i32, i32, i32, u32, i32, *const c_void) = glCompressedTexSubImage2D;
    let _: unsafe extern "C" fn(u32, i32, u32, i32, i32, i32, i32, i32) = glCopyTexImage2D;
    let _: unsafe extern "C" fn(u32, i32, i32, i32, i32, i32, i32, i32) = glCopyTexSubImage2D;
    let _: unsafe extern "C" fn() -> u32 = glCreateProgram;
    let _: unsafe extern "C" fn(u32) -> u32 = glCreateShader;
    let _: unsafe extern "C" fn(u32) = glCullFace;
    let _: unsafe extern "C" fn(i32, *const c_void) = glDeleteBuffers;
    let _: unsafe extern "C" fn(i32, *const c_void) = glDeleteFramebuffers;
    let _: unsafe extern "C" fn(u32) = glDeleteProgram;
    let _: unsafe extern "C" fn(i32, *const c_void) = glDeleteRenderbuffers;
    let _: unsafe extern "C" fn(u32) = glDeleteShader;
    let _: unsafe extern "C" fn(i32, *const c_void) = glDeleteTextures;
    let _: unsafe extern "C" fn(u32) = glDepthFunc;
    let _: unsafe extern "C" fn(u8) = glDepthMask;
    let _: unsafe extern "C" fn(f32, f32) = glDepthRangef;
    let _: unsafe extern "C" fn(u32, u32) = glDetachShader;
    let _: unsafe extern "C" fn(u32) = glDisable;
    let _: unsafe extern "C" fn(u32) = glDisableVertexAttribArray;
    let _: unsafe extern "C" fn(u32, i32, i32) = glDrawArrays;
    let _: unsafe extern "C" fn(u32, i32, u32, *const c_void) = glDrawElements;
    let _: unsafe extern "C" fn(u32) = glEnable;
    let _: unsafe extern "C" fn(u32) = glEnableVertexAttribArray;
    let _: unsafe extern "C" fn() = glFinish;
    let _: unsafe extern "C" fn() = glFlush;
    let _: unsafe extern "C" fn(u32, u32, u32, u32) = glFramebufferRenderbuffer;
    let _: unsafe extern "C" fn(u32, u32, u32, u32, i32) = glFramebufferTexture2D;
    let _: unsafe extern "C" fn(u32) = glFrontFace;
    let _: unsafe extern "C" fn(i32, *mut c_void) = glGenBuffers;
    let _: unsafe extern "C" fn(u32) = glGenerateMipmap;
    let _: unsafe extern "C" fn(i32, *mut c_void) = glGenFramebuffers;
    let _: unsafe extern "C" fn(i32, *mut c_void) = glGenRenderbuffers;
    let _: unsafe extern "C" fn(i32, *mut c_void) = glGenTextures;
    let _: unsafe extern "C" fn(u32, u32, i32, *mut c_void, *mut c_void, *mut c_void, *mut c_void) = glGetActiveAttrib;
    let _: unsafe extern "C" fn(u32, u32, i32, *mut c_void, *mut c_void, *mut c_void, *mut c_void) = glGetActiveUniform;
    let _: unsafe extern "C" fn(u32, i32, *mut c_void, *mut c_void) = glGetAttachedShaders;
    let _: unsafe extern "C" fn(u32, *const c_void) -> i32 = glGetAttribLocation;
    let _: unsafe extern "C" fn(u32, *mut c_void) = glGetBooleanv;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetBufferParameteriv;
    let _: unsafe extern "C" fn() -> u32 = glGetError;
    let _: unsafe extern "C" fn(u32, *mut c_void) = glGetFloatv;
    let _: unsafe extern "C" fn(u32, u32, u32, *mut c_void) = glGetFramebufferAttachmentParameteriv;
    let _: unsafe extern "C" fn(u32, *mut c_void) = glGetIntegerv;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetProgramiv;
    let _: unsafe extern "C" fn(u32, i32, *mut c_void, *mut c_void) = glGetProgramInfoLog;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetRenderbufferParameteriv;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetShaderiv;
    let _: unsafe extern "C" fn(u32, i32, *mut c_void, *mut c_void) = glGetShaderInfoLog;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void, *mut c_void) = glGetShaderPrecisionFormat;
    let _: unsafe extern "C" fn(u32, i32, *mut c_void, *mut c_void) = glGetShaderSource;
    let _: unsafe extern "C" fn(u32) -> *const c_void = glGetString;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetTexParameterfv;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetTexParameteriv;
    let _: unsafe extern "C" fn(u32, i32, *mut c_void) = glGetUniformfv;
    let _: unsafe extern "C" fn(u32, i32, *mut c_void) = glGetUniformiv;
    let _: unsafe extern "C" fn(u32, *const c_void) -> i32 = glGetUniformLocation;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetVertexAttribfv;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetVertexAttribiv;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetVertexAttribPointerv;
    let _: unsafe extern "C" fn(u32, u32) = glHint;
    let _: unsafe extern "C" fn(u32) -> u8 = glIsBuffer;
    let _: unsafe extern "C" fn(u32) -> u8 = glIsEnabled;
    let _: unsafe extern "C" fn(u32) -> u8 = glIsFramebuffer;
    let _: unsafe extern "C" fn(u32) -> u8 = glIsProgram;
    let _: unsafe extern "C" fn(u32) -> u8 = glIsRenderbuffer;
    let _: unsafe extern "C" fn(u32) -> u8 = glIsShader;
    let _: unsafe extern "C" fn(u32) -> u8 = glIsTexture;
    let _: unsafe extern "C" fn(f32) = glLineWidth;
    let _: unsafe extern "C" fn(u32) = glLinkProgram;
    let _: unsafe extern "C" fn(u32, i32) = glPixelStorei;
    let _: unsafe extern "C" fn(f32, f32) = glPolygonOffset;
    let _: unsafe extern "C" fn(i32, i32, i32, i32, u32, u32, *mut c_void) = glReadPixels;
    let _: unsafe extern "C" fn() = glReleaseShaderCompiler;
    let _: unsafe extern "C" fn(u32, u32, i32, i32) = glRenderbufferStorage;
    let _: unsafe extern "C" fn(f32, u8) = glSampleCoverage;
    let _: unsafe extern "C" fn(i32, i32, i32, i32) = glScissor;
    let _: unsafe extern "C" fn(i32, *const c_void, u32, *const c_void, i32) = glShaderBinary;
    let _: unsafe extern "C" fn(u32, i32, *const c_void, *const c_void) = glShaderSource;
    let _: unsafe extern "C" fn(u32, i32, u32) = glStencilFunc;
    let _: unsafe extern "C" fn(u32, u32, i32, u32) = glStencilFuncSeparate;
    let _: unsafe extern "C" fn(u32) = glStencilMask;
    let _: unsafe extern "C" fn(u32, u32) = glStencilMaskSeparate;
    let _: unsafe extern "C" fn(u32, u32, u32) = glStencilOp;
    let _: unsafe extern "C" fn(u32, u32, u32, u32) = glStencilOpSeparate;
    let _: unsafe extern "C" fn(u32, i32, i32, i32, i32, i32, u32, u32, *const c_void) = glTexImage2D;
    let _: unsafe extern "C" fn(u32, u32, f32) = glTexParameterf;
    let _: unsafe extern "C" fn(u32, u32, *const c_void) = glTexParameterfv;
    let _: unsafe extern "C" fn(u32, u32, i32) = glTexParameteri;
    let _: unsafe extern "C" fn(u32, u32, *const c_void) = glTexParameteriv;
    let _: unsafe extern "C" fn(u32, i32, i32, i32, i32, i32, u32, u32, *const c_void) = glTexSubImage2D;
    let _: unsafe extern "C" fn(i32, f32) = glUniform1f;
    let _: unsafe extern "C" fn(i32, i32, *const c_void) = glUniform1fv;
    let _: unsafe extern "C" fn(i32, i32) = glUniform1i;
    let _: unsafe extern "C" fn(i32, i32, *const c_void) = glUniform1iv;
    let _: unsafe extern "C" fn(i32, f32, f32) = glUniform2f;
    let _: unsafe extern "C" fn(i32, i32, *const c_void) = glUniform2fv;
    let _: unsafe extern "C" fn(i32, i32, i32) = glUniform2i;
    let _: unsafe extern "C" fn(i32, i32, *const c_void) = glUniform2iv;
    let _: unsafe extern "C" fn(i32, f32, f32, f32) = glUniform3f;
    let _: unsafe extern "C" fn(i32, i32, *const c_void) = glUniform3fv;
    let _: unsafe extern "C" fn(i32, i32, i32, i32) = glUniform3i;
    let _: unsafe extern "C" fn(i32, i32, *const c_void) = glUniform3iv;
    let _: unsafe extern "C" fn(i32, f32, f32, f32, f32) = glUniform4f;
    let _: unsafe extern "C" fn(i32, i32, *const c_void) = glUniform4fv;
    let _: unsafe extern "C" fn(i32, i32, i32, i32, i32) = glUniform4i;
    let _: unsafe extern "C" fn(i32, i32, *const c_void) = glUniform4iv;
    let _: unsafe extern "C" fn(i32, i32, u8, *const c_void) = glUniformMatrix2fv;
    let _: unsafe extern "C" fn(i32, i32, u8, *const c_void) = glUniformMatrix3fv;
    let _: unsafe extern "C" fn(i32, i32, u8, *const c_void) = glUniformMatrix4fv;
    let _: unsafe extern "C" fn(u32) = glUseProgram;
    let _: unsafe extern "C" fn(u32) = glValidateProgram;
    let _: unsafe extern "C" fn(u32, f32) = glVertexAttrib1f;
    let _: unsafe extern "C" fn(u32, *const c_void) = glVertexAttrib1fv;
    let _: unsafe extern "C" fn(u32, f32, f32) = glVertexAttrib2f;
    let _: unsafe extern "C" fn(u32, *const c_void) = glVertexAttrib2fv;
    let _: unsafe extern "C" fn(u32, f32, f32, f32) = glVertexAttrib3f;
    let _: unsafe extern "C" fn(u32, *const c_void) = glVertexAttrib3fv;
    let _: unsafe extern "C" fn(u32, f32, f32, f32, f32) = glVertexAttrib4f;
    let _: unsafe extern "C" fn(u32, *const c_void) = glVertexAttrib4fv;
    let _: unsafe extern "C" fn(u32, i32, u32, u8, i32, *const c_void) = glVertexAttribPointer;
    let _: unsafe extern "C" fn(i32, i32, i32, i32) = glViewport;
    let _: unsafe extern "C" fn(u32) = glReadBuffer;
    let _: unsafe extern "C" fn(u32, u32, u32, i32, u32, *const c_void) = glDrawRangeElements;
    let _: unsafe extern "C" fn(u32, i32, i32, i32, i32, i32, i32, u32, u32, *const c_void) = glTexImage3D;
    let _: unsafe extern "C" fn(u32, i32, i32, i32, i32, i32, i32, i32, u32, u32, *const c_void) = glTexSubImage3D;
    let _: unsafe extern "C" fn(u32, i32, i32, i32, i32, i32, i32, i32, i32) = glCopyTexSubImage3D;
    let _: unsafe extern "C" fn(u32, i32, u32, i32, i32, i32, i32, i32, *const c_void) = glCompressedTexImage3D;
    let _: unsafe extern "C" fn(u32, i32, i32, i32, i32, i32, i32, i32, u32, i32, *const c_void) = glCompressedTexSubImage3D;
    let _: unsafe extern "C" fn(i32, *mut c_void) = glGenQueries;
    let _: unsafe extern "C" fn(i32, *const c_void) = glDeleteQueries;
    let _: unsafe extern "C" fn(u32) -> u8 = glIsQuery;
    let _: unsafe extern "C" fn(u32, u32) = glBeginQuery;
    let _: unsafe extern "C" fn(u32) = glEndQuery;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetQueryiv;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetQueryObjectuiv;
    let _: unsafe extern "C" fn(u32) -> u8 = glUnmapBuffer;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetBufferPointerv;
    let _: unsafe extern "C" fn(i32, *const c_void) = glDrawBuffers;
    let _: unsafe extern "C" fn(i32, i32, u8, *const c_void) = glUniformMatrix2x3fv;
    let _: unsafe extern "C" fn(i32, i32, u8, *const c_void) = glUniformMatrix3x2fv;
    let _: unsafe extern "C" fn(i32, i32, u8, *const c_void) = glUniformMatrix2x4fv;
    let _: unsafe extern "C" fn(i32, i32, u8, *const c_void) = glUniformMatrix4x2fv;
    let _: unsafe extern "C" fn(i32, i32, u8, *const c_void) = glUniformMatrix3x4fv;
    let _: unsafe extern "C" fn(i32, i32, u8, *const c_void) = glUniformMatrix4x3fv;
    let _: unsafe extern "C" fn(i32, i32, i32, i32, i32, i32, i32, i32, u32, u32) = glBlitFramebuffer;
    let _: unsafe extern "C" fn(u32, i32, u32, i32, i32) = glRenderbufferStorageMultisample;
    let _: unsafe extern "C" fn(u32, u32, u32, i32, i32) = glFramebufferTextureLayer;
    let _: unsafe extern "C" fn(u32, isize, isize, u32) -> *mut c_void = glMapBufferRange;
    let _: unsafe extern "C" fn(u32, isize, isize) = glFlushMappedBufferRange;
    let _: unsafe extern "C" fn(u32) = glBindVertexArray;
    let _: unsafe extern "C" fn(i32, *const c_void) = glDeleteVertexArrays;
    let _: unsafe extern "C" fn(i32, *mut c_void) = glGenVertexArrays;
    let _: unsafe extern "C" fn(u32) -> u8 = glIsVertexArray;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetIntegeri_v;
    let _: unsafe extern "C" fn(u32) = glBeginTransformFeedback;
    let _: unsafe extern "C" fn() = glEndTransformFeedback;
    let _: unsafe extern "C" fn(u32, u32, u32, isize, isize) = glBindBufferRange;
    let _: unsafe extern "C" fn(u32, u32, u32) = glBindBufferBase;
    let _: unsafe extern "C" fn(u32, i32, *const c_void, u32) = glTransformFeedbackVaryings;
    let _: unsafe extern "C" fn(u32, u32, i32, *mut c_void, *mut c_void, *mut c_void, *mut c_void) = glGetTransformFeedbackVarying;
    let _: unsafe extern "C" fn(u32, i32, u32, i32, *const c_void) = glVertexAttribIPointer;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetVertexAttribIiv;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetVertexAttribIuiv;
    let _: unsafe extern "C" fn(u32, i32, i32, i32, i32) = glVertexAttribI4i;
    let _: unsafe extern "C" fn(u32, u32, u32, u32, u32) = glVertexAttribI4ui;
    let _: unsafe extern "C" fn(u32, *const c_void) = glVertexAttribI4iv;
    let _: unsafe extern "C" fn(u32, *const c_void) = glVertexAttribI4uiv;
    let _: unsafe extern "C" fn(u32, i32, *mut c_void) = glGetUniformuiv;
    let _: unsafe extern "C" fn(u32, *const c_void) -> i32 = glGetFragDataLocation;
    let _: unsafe extern "C" fn(i32, u32) = glUniform1ui;
    let _: unsafe extern "C" fn(i32, u32, u32) = glUniform2ui;
    let _: unsafe extern "C" fn(i32, u32, u32, u32) = glUniform3ui;
    let _: unsafe extern "C" fn(i32, u32, u32, u32, u32) = glUniform4ui;
    let _: unsafe extern "C" fn(i32, i32, *const c_void) = glUniform1uiv;
    let _: unsafe extern "C" fn(i32, i32, *const c_void) = glUniform2uiv;
    let _: unsafe extern "C" fn(i32, i32, *const c_void) = glUniform3uiv;
    let _: unsafe extern "C" fn(i32, i32, *const c_void) = glUniform4uiv;
    let _: unsafe extern "C" fn(u32, i32, *const c_void) = glClearBufferiv;
    let _: unsafe extern "C" fn(u32, i32, *const c_void) = glClearBufferuiv;
    let _: unsafe extern "C" fn(u32, i32, *const c_void) = glClearBufferfv;
    let _: unsafe extern "C" fn(u32, i32, f32, i32) = glClearBufferfi;
    let _: unsafe extern "C" fn(u32, u32) -> *const c_void = glGetStringi;
    let _: unsafe extern "C" fn(u32, u32, isize, isize, isize) = glCopyBufferSubData;
    let _: unsafe extern "C" fn(u32, i32, *const c_void, *mut c_void) = glGetUniformIndices;
    let _: unsafe extern "C" fn(u32, i32, *const c_void, u32, *mut c_void) = glGetActiveUniformsiv;
    let _: unsafe extern "C" fn(u32, *const c_void) -> u32 = glGetUniformBlockIndex;
    let _: unsafe extern "C" fn(u32, u32, u32, *mut c_void) = glGetActiveUniformBlockiv;
    let _: unsafe extern "C" fn(u32, u32, i32, *mut c_void, *mut c_void) = glGetActiveUniformBlockName;
    let _: unsafe extern "C" fn(u32, u32, u32) = glUniformBlockBinding;
    let _: unsafe extern "C" fn(u32, i32, i32, i32) = glDrawArraysInstanced;
    let _: unsafe extern "C" fn(u32, i32, u32, *const c_void, i32) = glDrawElementsInstanced;
    let _: unsafe extern "C" fn(u32, u32) -> *const c_void = glFenceSync;
    let _: unsafe extern "C" fn(*const c_void) -> u8 = glIsSync;
    let _: unsafe extern "C" fn(*const c_void) = glDeleteSync;
    let _: unsafe extern "C" fn(*const c_void, u32, u64) -> u32 = glClientWaitSync;
    let _: unsafe extern "C" fn(*const c_void, u32, u64) = glWaitSync;
    let _: unsafe extern "C" fn(u32, *mut c_void) = glGetInteger64v;
    let _: unsafe extern "C" fn(*const c_void, u32, i32, *mut c_void, *mut c_void) = glGetSynciv;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetInteger64i_v;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetBufferParameteri64v;
    let _: unsafe extern "C" fn(i32, *mut c_void) = glGenSamplers;
    let _: unsafe extern "C" fn(i32, *const c_void) = glDeleteSamplers;
    let _: unsafe extern "C" fn(u32) -> u8 = glIsSampler;
    let _: unsafe extern "C" fn(u32, u32) = glBindSampler;
    let _: unsafe extern "C" fn(u32, u32, i32) = glSamplerParameteri;
    let _: unsafe extern "C" fn(u32, u32, *const c_void) = glSamplerParameteriv;
    let _: unsafe extern "C" fn(u32, u32, f32) = glSamplerParameterf;
    let _: unsafe extern "C" fn(u32, u32, *const c_void) = glSamplerParameterfv;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetSamplerParameteriv;
    let _: unsafe extern "C" fn(u32, u32, *mut c_void) = glGetSamplerParameterfv;
    let _: unsafe extern "C" fn(u32, u32) = glVertexAttribDivisor;
    let _: unsafe extern "C" fn(u32, u32) = glBindTransformFeedback;
    let _: unsafe extern "C" fn(i32, *const c_void) = glDeleteTransformFeedbacks;
    let _: unsafe extern "C" fn(i32, *mut c_void) = glGenTransformFeedbacks;
    let _: unsafe extern "C" fn(u32) -> u8 = glIsTransformFeedback;
    let _: unsafe extern "C" fn() = glPauseTransformFeedback;
    let _: unsafe extern "C" fn() = glResumeTransformFeedback;
    let _: unsafe extern "C" fn(u32, i32, *mut c_void, *mut c_void, *mut c_void) = glGetProgramBinary;
    let _: unsafe extern "C" fn(u32, u32, *const c_void, i32) = glProgramBinary;
    let _: unsafe extern "C" fn(u32, u32, i32) = glProgramParameteri;
    let _: unsafe extern "C" fn(u32, i32, *const c_void) = glInvalidateFramebuffer;
    let _: unsafe extern "C" fn(u32, i32, *const c_void, i32, i32, i32, i32) = glInvalidateSubFramebuffer;
    let _: unsafe extern "C" fn(u32, i32, u32, i32, i32) = glTexStorage2D;
    let _: unsafe extern "C" fn(u32, i32, u32, i32, i32, i32) = glTexStorage3D;
    let _: unsafe extern "C" fn(u32, u32, u32, i32, *mut c_void) = glGetInternalformativ;
};

/// The function `name` (a GLES 3.0 entry point), or null.
pub fn lookup(name: &[u8]) -> *const c_void {
    match name {
        b"glActiveTexture" => glActiveTexture as *const c_void,
        b"glAttachShader" => glAttachShader as *const c_void,
        b"glBindAttribLocation" => glBindAttribLocation as *const c_void,
        b"glBindBuffer" => glBindBuffer as *const c_void,
        b"glBindFramebuffer" => glBindFramebuffer as *const c_void,
        b"glBindRenderbuffer" => glBindRenderbuffer as *const c_void,
        b"glBindTexture" => glBindTexture as *const c_void,
        b"glBlendColor" => glBlendColor as *const c_void,
        b"glBlendEquation" => glBlendEquation as *const c_void,
        b"glBlendEquationSeparate" => glBlendEquationSeparate as *const c_void,
        b"glBlendFunc" => glBlendFunc as *const c_void,
        b"glBlendFuncSeparate" => glBlendFuncSeparate as *const c_void,
        b"glBufferData" => glBufferData as *const c_void,
        b"glBufferSubData" => glBufferSubData as *const c_void,
        b"glCheckFramebufferStatus" => glCheckFramebufferStatus as *const c_void,
        b"glClear" => glClear as *const c_void,
        b"glClearColor" => glClearColor as *const c_void,
        b"glClearDepthf" => glClearDepthf as *const c_void,
        b"glClearStencil" => glClearStencil as *const c_void,
        b"glColorMask" => glColorMask as *const c_void,
        b"glCompileShader" => glCompileShader as *const c_void,
        b"glCompressedTexImage2D" => glCompressedTexImage2D as *const c_void,
        b"glCompressedTexSubImage2D" => glCompressedTexSubImage2D as *const c_void,
        b"glCopyTexImage2D" => glCopyTexImage2D as *const c_void,
        b"glCopyTexSubImage2D" => glCopyTexSubImage2D as *const c_void,
        b"glCreateProgram" => glCreateProgram as *const c_void,
        b"glCreateShader" => glCreateShader as *const c_void,
        b"glCullFace" => glCullFace as *const c_void,
        b"glDeleteBuffers" => glDeleteBuffers as *const c_void,
        b"glDeleteFramebuffers" => glDeleteFramebuffers as *const c_void,
        b"glDeleteProgram" => glDeleteProgram as *const c_void,
        b"glDeleteRenderbuffers" => glDeleteRenderbuffers as *const c_void,
        b"glDeleteShader" => glDeleteShader as *const c_void,
        b"glDeleteTextures" => glDeleteTextures as *const c_void,
        b"glDepthFunc" => glDepthFunc as *const c_void,
        b"glDepthMask" => glDepthMask as *const c_void,
        b"glDepthRangef" => glDepthRangef as *const c_void,
        b"glDetachShader" => glDetachShader as *const c_void,
        b"glDisable" => glDisable as *const c_void,
        b"glDisableVertexAttribArray" => glDisableVertexAttribArray as *const c_void,
        b"glDrawArrays" => glDrawArrays as *const c_void,
        b"glDrawElements" => glDrawElements as *const c_void,
        b"glEnable" => glEnable as *const c_void,
        b"glEnableVertexAttribArray" => glEnableVertexAttribArray as *const c_void,
        b"glFinish" => glFinish as *const c_void,
        b"glFlush" => glFlush as *const c_void,
        b"glFramebufferRenderbuffer" => glFramebufferRenderbuffer as *const c_void,
        b"glFramebufferTexture2D" => glFramebufferTexture2D as *const c_void,
        b"glFrontFace" => glFrontFace as *const c_void,
        b"glGenBuffers" => glGenBuffers as *const c_void,
        b"glGenerateMipmap" => glGenerateMipmap as *const c_void,
        b"glGenFramebuffers" => glGenFramebuffers as *const c_void,
        b"glGenRenderbuffers" => glGenRenderbuffers as *const c_void,
        b"glGenTextures" => glGenTextures as *const c_void,
        b"glGetActiveAttrib" => glGetActiveAttrib as *const c_void,
        b"glGetActiveUniform" => glGetActiveUniform as *const c_void,
        b"glGetAttachedShaders" => glGetAttachedShaders as *const c_void,
        b"glGetAttribLocation" => glGetAttribLocation as *const c_void,
        b"glGetBooleanv" => glGetBooleanv as *const c_void,
        b"glGetBufferParameteriv" => glGetBufferParameteriv as *const c_void,
        b"glGetError" => glGetError as *const c_void,
        b"glGetFloatv" => glGetFloatv as *const c_void,
        b"glGetFramebufferAttachmentParameteriv" => glGetFramebufferAttachmentParameteriv as *const c_void,
        b"glGetIntegerv" => glGetIntegerv as *const c_void,
        b"glGetProgramiv" => glGetProgramiv as *const c_void,
        b"glGetProgramInfoLog" => glGetProgramInfoLog as *const c_void,
        b"glGetRenderbufferParameteriv" => glGetRenderbufferParameteriv as *const c_void,
        b"glGetShaderiv" => glGetShaderiv as *const c_void,
        b"glGetShaderInfoLog" => glGetShaderInfoLog as *const c_void,
        b"glGetShaderPrecisionFormat" => glGetShaderPrecisionFormat as *const c_void,
        b"glGetShaderSource" => glGetShaderSource as *const c_void,
        b"glGetString" => glGetString as *const c_void,
        b"glGetTexParameterfv" => glGetTexParameterfv as *const c_void,
        b"glGetTexParameteriv" => glGetTexParameteriv as *const c_void,
        b"glGetUniformfv" => glGetUniformfv as *const c_void,
        b"glGetUniformiv" => glGetUniformiv as *const c_void,
        b"glGetUniformLocation" => glGetUniformLocation as *const c_void,
        b"glGetVertexAttribfv" => glGetVertexAttribfv as *const c_void,
        b"glGetVertexAttribiv" => glGetVertexAttribiv as *const c_void,
        b"glGetVertexAttribPointerv" => glGetVertexAttribPointerv as *const c_void,
        b"glHint" => glHint as *const c_void,
        b"glIsBuffer" => glIsBuffer as *const c_void,
        b"glIsEnabled" => glIsEnabled as *const c_void,
        b"glIsFramebuffer" => glIsFramebuffer as *const c_void,
        b"glIsProgram" => glIsProgram as *const c_void,
        b"glIsRenderbuffer" => glIsRenderbuffer as *const c_void,
        b"glIsShader" => glIsShader as *const c_void,
        b"glIsTexture" => glIsTexture as *const c_void,
        b"glLineWidth" => glLineWidth as *const c_void,
        b"glLinkProgram" => glLinkProgram as *const c_void,
        b"glPixelStorei" => glPixelStorei as *const c_void,
        b"glPolygonOffset" => glPolygonOffset as *const c_void,
        b"glReadPixels" => glReadPixels as *const c_void,
        b"glReleaseShaderCompiler" => glReleaseShaderCompiler as *const c_void,
        b"glRenderbufferStorage" => glRenderbufferStorage as *const c_void,
        b"glSampleCoverage" => glSampleCoverage as *const c_void,
        b"glScissor" => glScissor as *const c_void,
        b"glShaderBinary" => glShaderBinary as *const c_void,
        b"glShaderSource" => glShaderSource as *const c_void,
        b"glStencilFunc" => glStencilFunc as *const c_void,
        b"glStencilFuncSeparate" => glStencilFuncSeparate as *const c_void,
        b"glStencilMask" => glStencilMask as *const c_void,
        b"glStencilMaskSeparate" => glStencilMaskSeparate as *const c_void,
        b"glStencilOp" => glStencilOp as *const c_void,
        b"glStencilOpSeparate" => glStencilOpSeparate as *const c_void,
        b"glTexImage2D" => glTexImage2D as *const c_void,
        b"glTexParameterf" => glTexParameterf as *const c_void,
        b"glTexParameterfv" => glTexParameterfv as *const c_void,
        b"glTexParameteri" => glTexParameteri as *const c_void,
        b"glTexParameteriv" => glTexParameteriv as *const c_void,
        b"glTexSubImage2D" => glTexSubImage2D as *const c_void,
        b"glUniform1f" => glUniform1f as *const c_void,
        b"glUniform1fv" => glUniform1fv as *const c_void,
        b"glUniform1i" => glUniform1i as *const c_void,
        b"glUniform1iv" => glUniform1iv as *const c_void,
        b"glUniform2f" => glUniform2f as *const c_void,
        b"glUniform2fv" => glUniform2fv as *const c_void,
        b"glUniform2i" => glUniform2i as *const c_void,
        b"glUniform2iv" => glUniform2iv as *const c_void,
        b"glUniform3f" => glUniform3f as *const c_void,
        b"glUniform3fv" => glUniform3fv as *const c_void,
        b"glUniform3i" => glUniform3i as *const c_void,
        b"glUniform3iv" => glUniform3iv as *const c_void,
        b"glUniform4f" => glUniform4f as *const c_void,
        b"glUniform4fv" => glUniform4fv as *const c_void,
        b"glUniform4i" => glUniform4i as *const c_void,
        b"glUniform4iv" => glUniform4iv as *const c_void,
        b"glUniformMatrix2fv" => glUniformMatrix2fv as *const c_void,
        b"glUniformMatrix3fv" => glUniformMatrix3fv as *const c_void,
        b"glUniformMatrix4fv" => glUniformMatrix4fv as *const c_void,
        b"glUseProgram" => glUseProgram as *const c_void,
        b"glValidateProgram" => glValidateProgram as *const c_void,
        b"glVertexAttrib1f" => glVertexAttrib1f as *const c_void,
        b"glVertexAttrib1fv" => glVertexAttrib1fv as *const c_void,
        b"glVertexAttrib2f" => glVertexAttrib2f as *const c_void,
        b"glVertexAttrib2fv" => glVertexAttrib2fv as *const c_void,
        b"glVertexAttrib3f" => glVertexAttrib3f as *const c_void,
        b"glVertexAttrib3fv" => glVertexAttrib3fv as *const c_void,
        b"glVertexAttrib4f" => glVertexAttrib4f as *const c_void,
        b"glVertexAttrib4fv" => glVertexAttrib4fv as *const c_void,
        b"glVertexAttribPointer" => glVertexAttribPointer as *const c_void,
        b"glViewport" => glViewport as *const c_void,
        b"glReadBuffer" => glReadBuffer as *const c_void,
        b"glDrawRangeElements" => glDrawRangeElements as *const c_void,
        b"glTexImage3D" => glTexImage3D as *const c_void,
        b"glTexSubImage3D" => glTexSubImage3D as *const c_void,
        b"glCopyTexSubImage3D" => glCopyTexSubImage3D as *const c_void,
        b"glCompressedTexImage3D" => glCompressedTexImage3D as *const c_void,
        b"glCompressedTexSubImage3D" => glCompressedTexSubImage3D as *const c_void,
        b"glGenQueries" => glGenQueries as *const c_void,
        b"glDeleteQueries" => glDeleteQueries as *const c_void,
        b"glIsQuery" => glIsQuery as *const c_void,
        b"glBeginQuery" => glBeginQuery as *const c_void,
        b"glEndQuery" => glEndQuery as *const c_void,
        b"glGetQueryiv" => glGetQueryiv as *const c_void,
        b"glGetQueryObjectuiv" => glGetQueryObjectuiv as *const c_void,
        b"glUnmapBuffer" => glUnmapBuffer as *const c_void,
        b"glGetBufferPointerv" => glGetBufferPointerv as *const c_void,
        b"glDrawBuffers" => glDrawBuffers as *const c_void,
        b"glUniformMatrix2x3fv" => glUniformMatrix2x3fv as *const c_void,
        b"glUniformMatrix3x2fv" => glUniformMatrix3x2fv as *const c_void,
        b"glUniformMatrix2x4fv" => glUniformMatrix2x4fv as *const c_void,
        b"glUniformMatrix4x2fv" => glUniformMatrix4x2fv as *const c_void,
        b"glUniformMatrix3x4fv" => glUniformMatrix3x4fv as *const c_void,
        b"glUniformMatrix4x3fv" => glUniformMatrix4x3fv as *const c_void,
        b"glBlitFramebuffer" => glBlitFramebuffer as *const c_void,
        b"glRenderbufferStorageMultisample" => glRenderbufferStorageMultisample as *const c_void,
        b"glFramebufferTextureLayer" => glFramebufferTextureLayer as *const c_void,
        b"glMapBufferRange" => glMapBufferRange as *const c_void,
        b"glFlushMappedBufferRange" => glFlushMappedBufferRange as *const c_void,
        b"glBindVertexArray" => glBindVertexArray as *const c_void,
        b"glDeleteVertexArrays" => glDeleteVertexArrays as *const c_void,
        b"glGenVertexArrays" => glGenVertexArrays as *const c_void,
        b"glIsVertexArray" => glIsVertexArray as *const c_void,
        b"glGetIntegeri_v" => glGetIntegeri_v as *const c_void,
        b"glBeginTransformFeedback" => glBeginTransformFeedback as *const c_void,
        b"glEndTransformFeedback" => glEndTransformFeedback as *const c_void,
        b"glBindBufferRange" => glBindBufferRange as *const c_void,
        b"glBindBufferBase" => glBindBufferBase as *const c_void,
        b"glTransformFeedbackVaryings" => glTransformFeedbackVaryings as *const c_void,
        b"glGetTransformFeedbackVarying" => glGetTransformFeedbackVarying as *const c_void,
        b"glVertexAttribIPointer" => glVertexAttribIPointer as *const c_void,
        b"glGetVertexAttribIiv" => glGetVertexAttribIiv as *const c_void,
        b"glGetVertexAttribIuiv" => glGetVertexAttribIuiv as *const c_void,
        b"glVertexAttribI4i" => glVertexAttribI4i as *const c_void,
        b"glVertexAttribI4ui" => glVertexAttribI4ui as *const c_void,
        b"glVertexAttribI4iv" => glVertexAttribI4iv as *const c_void,
        b"glVertexAttribI4uiv" => glVertexAttribI4uiv as *const c_void,
        b"glGetUniformuiv" => glGetUniformuiv as *const c_void,
        b"glGetFragDataLocation" => glGetFragDataLocation as *const c_void,
        b"glUniform1ui" => glUniform1ui as *const c_void,
        b"glUniform2ui" => glUniform2ui as *const c_void,
        b"glUniform3ui" => glUniform3ui as *const c_void,
        b"glUniform4ui" => glUniform4ui as *const c_void,
        b"glUniform1uiv" => glUniform1uiv as *const c_void,
        b"glUniform2uiv" => glUniform2uiv as *const c_void,
        b"glUniform3uiv" => glUniform3uiv as *const c_void,
        b"glUniform4uiv" => glUniform4uiv as *const c_void,
        b"glClearBufferiv" => glClearBufferiv as *const c_void,
        b"glClearBufferuiv" => glClearBufferuiv as *const c_void,
        b"glClearBufferfv" => glClearBufferfv as *const c_void,
        b"glClearBufferfi" => glClearBufferfi as *const c_void,
        b"glGetStringi" => glGetStringi as *const c_void,
        b"glCopyBufferSubData" => glCopyBufferSubData as *const c_void,
        b"glGetUniformIndices" => glGetUniformIndices as *const c_void,
        b"glGetActiveUniformsiv" => glGetActiveUniformsiv as *const c_void,
        b"glGetUniformBlockIndex" => glGetUniformBlockIndex as *const c_void,
        b"glGetActiveUniformBlockiv" => glGetActiveUniformBlockiv as *const c_void,
        b"glGetActiveUniformBlockName" => glGetActiveUniformBlockName as *const c_void,
        b"glUniformBlockBinding" => glUniformBlockBinding as *const c_void,
        b"glDrawArraysInstanced" => glDrawArraysInstanced as *const c_void,
        b"glDrawElementsInstanced" => glDrawElementsInstanced as *const c_void,
        b"glFenceSync" => glFenceSync as *const c_void,
        b"glIsSync" => glIsSync as *const c_void,
        b"glDeleteSync" => glDeleteSync as *const c_void,
        b"glClientWaitSync" => glClientWaitSync as *const c_void,
        b"glWaitSync" => glWaitSync as *const c_void,
        b"glGetInteger64v" => glGetInteger64v as *const c_void,
        b"glGetSynciv" => glGetSynciv as *const c_void,
        b"glGetInteger64i_v" => glGetInteger64i_v as *const c_void,
        b"glGetBufferParameteri64v" => glGetBufferParameteri64v as *const c_void,
        b"glGenSamplers" => glGenSamplers as *const c_void,
        b"glDeleteSamplers" => glDeleteSamplers as *const c_void,
        b"glIsSampler" => glIsSampler as *const c_void,
        b"glBindSampler" => glBindSampler as *const c_void,
        b"glSamplerParameteri" => glSamplerParameteri as *const c_void,
        b"glSamplerParameteriv" => glSamplerParameteriv as *const c_void,
        b"glSamplerParameterf" => glSamplerParameterf as *const c_void,
        b"glSamplerParameterfv" => glSamplerParameterfv as *const c_void,
        b"glGetSamplerParameteriv" => glGetSamplerParameteriv as *const c_void,
        b"glGetSamplerParameterfv" => glGetSamplerParameterfv as *const c_void,
        b"glVertexAttribDivisor" => glVertexAttribDivisor as *const c_void,
        b"glBindTransformFeedback" => glBindTransformFeedback as *const c_void,
        b"glDeleteTransformFeedbacks" => glDeleteTransformFeedbacks as *const c_void,
        b"glGenTransformFeedbacks" => glGenTransformFeedbacks as *const c_void,
        b"glIsTransformFeedback" => glIsTransformFeedback as *const c_void,
        b"glPauseTransformFeedback" => glPauseTransformFeedback as *const c_void,
        b"glResumeTransformFeedback" => glResumeTransformFeedback as *const c_void,
        b"glGetProgramBinary" => glGetProgramBinary as *const c_void,
        b"glProgramBinary" => glProgramBinary as *const c_void,
        b"glProgramParameteri" => glProgramParameteri as *const c_void,
        b"glInvalidateFramebuffer" => glInvalidateFramebuffer as *const c_void,
        b"glInvalidateSubFramebuffer" => glInvalidateSubFramebuffer as *const c_void,
        b"glTexStorage2D" => glTexStorage2D as *const c_void,
        b"glTexStorage3D" => glTexStorage3D as *const c_void,
        b"glGetInternalformativ" => glGetInternalformativ as *const c_void,
        _ => std::ptr::null(),
    }
}
